// Code generated by csn1c from TS 44.018 V19.0.0 §10.5.2.1e; DO NOT EDIT.
// Extracted source SHA-256: 36d2cf44fcc55fae7f2acb2dc10bf6be3eb416a2256c83d78f3859c6bd3b7556.
// Package cellselection contains typed CSN.1 codecs. Plain Encode calls preserve received layout and fail if an edit changes its semantic boundary. Encode<Type>Canonical copies the value, discards received layout, and checks that fresh encoding decodes to equivalent typed fields within a source-defined maximum. Definitions without a standalone maximum require Encode<Type>CanonicalAtLength with the containing value length; the default fails with runtime.ExtentError.
package cellselection

import (
	"fmt"
	"github.com/gomaja/go-csn1/runtime"
	ies "github.com/gomaja/go-csn1/ts44060/ies"
)

type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry struct {
	GSMDescription GSMDescriptionStruct
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription struct {
	GSMDescriptionList []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry struct {
	UTRANFDDDescription UTRANFDDDescriptionStruct
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription struct {
	UTRANFDDDescriptionList []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry struct {
	UTRANTDDDescription UTRANTDDDescriptionStruct
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription struct {
	UTRANTDDDescriptionList []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry struct {
	EUTRANDescription EUTRANDescriptionStruct
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription struct {
	EUTRANDescriptionList []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternative uint8

const (
	CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeGSMDescription      CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternative = iota
	CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeUTRANFDDDescription CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternative = iota
	CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeUTRANTDDDescription CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternative = iota
	CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeEUTRANDescription   CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternative = iota
)

type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice struct {
	Alternative         CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternative
	GSMDescription      *CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription
	UTRANFDDDescription *CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription
	UTRANTDDDescription *CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription
	EUTRANDescription   *CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription
}
type CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart struct {
	GSMDescriptionChoice CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice
	Wire                 runtime.WireInfo `json:"-"`
}
type GSMDescriptionStruct struct {
	BandIndicator uint8
	ARFCN         uint16
	BSIC          uint8
	Wire          runtime.WireInfo `json:"-"`
}
type UTRANFDDDescriptionStructFDDIndic0Group struct {
	FDDIndic0               uint8
	NROFFDDCELLS            uint8
	FDDCELLINFORMATIONField runtime.BitString
}
type UTRANFDDDescriptionStruct struct {
	BandwidthFDD   *uint8
	FDDARFCN       uint16
	FDDIndic0Group *UTRANFDDDescriptionStructFDDIndic0Group
	Wire           runtime.WireInfo `json:"-"`
}
type UTRANTDDDescriptionStructTDDIndic0Group struct {
	TDDIndic0               uint8
	NROFTDDCELLS            uint8
	TDDCELLINFORMATIONField runtime.BitString
}
type UTRANTDDDescriptionStruct struct {
	BandwidthTDD   *uint8
	TDDARFCN       uint16
	TDDIndic0Group *UTRANTDDDescriptionStructTDDIndic0Group
	Wire           runtime.WireInfo `json:"-"`
}
type EUTRANDescriptionStruct struct {
	EARFCN               uint16
	MeasurementBandwidth *uint8
	NotAllowedCells      *ies.PCIDGroupIE
	TARGETPCID           *uint16
	Wire                 runtime.WireInfo `json:"-"`
}

func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionAlt000(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionAlt000"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("000")
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionAlt000(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("000")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryAlt1(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryAlt1"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("1")
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryAlt1(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("1")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryGSMDescription(r *runtime.Reader) (GSMDescriptionStruct, error) {
	return decodeGSMDescriptionStruct(r)
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryGSMDescription(w *runtime.Writer, v GSMDescriptionStruct) error {
	return encodeGSMDescriptionStruct(w, v)
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryAlt1(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry{}, err
	}
	_ = x0
	x1, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryGSMDescription(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry{}, err
	}
	v.GSMDescription = x1
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryAlt1(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.GSMDescription) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GSMDescription")
	}
	if limit > 1 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntryGSMDescription(w, v.GSMDescription); err != nil {
			return err
		}
	}
	return nil
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionList(r *runtime.Reader) ([]CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry, error) {
	var out []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry
	terminated := false
	for r.Remaining() > 0 {
		if r.Matches("0") {
			if err := r.Expect("0"); err != nil {
				return nil, err
			}
			terminated = true
			break
		}
		before := r.Position()
		v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry(r)
		if err != nil {
			return nil, err
		}
		if r.Position() <= before {
			return nil, r.Error(runtime.Limit, "non-progressing repetition")
		}
		out = append(out, v)
	}
	if !terminated && !r.ZeroExtension() {
		return nil, r.Error(runtime.Truncated, "repetition terminator absent")
	}
	return out, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionList(w *runtime.Writer, v []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry) error {
	for _, item := range v {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionListEntry(w, item); err != nil {
			return err
		}
	}
	return w.WriteLiteral("0")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionAlt000(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription{}, err
	}
	_ = x0
	x1, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionList(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription{}, err
	}
	v.GSMDescriptionList = x1
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionAlt000(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.GSMDescriptionList) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GSMDescriptionList")
	}
	if limit > 1 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescriptionGSMDescriptionList(w, v.GSMDescriptionList); err != nil {
			return err
		}
	}
	return nil
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionAlt001(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionAlt001"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("001")
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionAlt001(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("001")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryAlt1(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryAlt1"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("1")
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryAlt1(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("1")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryUTRANFDDDescription(r *runtime.Reader) (UTRANFDDDescriptionStruct, error) {
	return decodeUTRANFDDDescriptionStruct(r)
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryUTRANFDDDescription(w *runtime.Writer, v UTRANFDDDescriptionStruct) error {
	return encodeUTRANFDDDescriptionStruct(w, v)
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryAlt1(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry{}, err
	}
	_ = x0
	x1, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryUTRANFDDDescription(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry{}, err
	}
	v.UTRANFDDDescription = x1
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryAlt1(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.UTRANFDDDescription) {
		return fmt.Errorf("edit to field beyond transmitted truncation: UTRANFDDDescription")
	}
	if limit > 1 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntryUTRANFDDDescription(w, v.UTRANFDDDescription); err != nil {
			return err
		}
	}
	return nil
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionList(r *runtime.Reader) ([]CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry, error) {
	var out []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry
	terminated := false
	for r.Remaining() > 0 {
		if r.Matches("0") {
			if err := r.Expect("0"); err != nil {
				return nil, err
			}
			terminated = true
			break
		}
		before := r.Position()
		v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry(r)
		if err != nil {
			return nil, err
		}
		if r.Position() <= before {
			return nil, r.Error(runtime.Limit, "non-progressing repetition")
		}
		out = append(out, v)
	}
	if !terminated && !r.ZeroExtension() {
		return nil, r.Error(runtime.Truncated, "repetition terminator absent")
	}
	return out, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionList(w *runtime.Writer, v []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry) error {
	for _, item := range v {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionListEntry(w, item); err != nil {
			return err
		}
	}
	return w.WriteLiteral("0")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionAlt001(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription{}, err
	}
	_ = x0
	x1, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionList(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription{}, err
	}
	v.UTRANFDDDescriptionList = x1
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionAlt001(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.UTRANFDDDescriptionList) {
		return fmt.Errorf("edit to field beyond transmitted truncation: UTRANFDDDescriptionList")
	}
	if limit > 1 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescriptionUTRANFDDDescriptionList(w, v.UTRANFDDDescriptionList); err != nil {
			return err
		}
	}
	return nil
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionAlt010(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionAlt010"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("010")
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionAlt010(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("010")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryAlt1(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryAlt1"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("1")
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryAlt1(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("1")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryUTRANTDDDescription(r *runtime.Reader) (UTRANTDDDescriptionStruct, error) {
	return decodeUTRANTDDDescriptionStruct(r)
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryUTRANTDDDescription(w *runtime.Writer, v UTRANTDDDescriptionStruct) error {
	return encodeUTRANTDDDescriptionStruct(w, v)
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryAlt1(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry{}, err
	}
	_ = x0
	x1, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryUTRANTDDDescription(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry{}, err
	}
	v.UTRANTDDDescription = x1
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryAlt1(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.UTRANTDDDescription) {
		return fmt.Errorf("edit to field beyond transmitted truncation: UTRANTDDDescription")
	}
	if limit > 1 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntryUTRANTDDDescription(w, v.UTRANTDDDescription); err != nil {
			return err
		}
	}
	return nil
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionList(r *runtime.Reader) ([]CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry, error) {
	var out []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry
	terminated := false
	for r.Remaining() > 0 {
		if r.Matches("0") {
			if err := r.Expect("0"); err != nil {
				return nil, err
			}
			terminated = true
			break
		}
		before := r.Position()
		v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry(r)
		if err != nil {
			return nil, err
		}
		if r.Position() <= before {
			return nil, r.Error(runtime.Limit, "non-progressing repetition")
		}
		out = append(out, v)
	}
	if !terminated && !r.ZeroExtension() {
		return nil, r.Error(runtime.Truncated, "repetition terminator absent")
	}
	return out, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionList(w *runtime.Writer, v []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry) error {
	for _, item := range v {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionListEntry(w, item); err != nil {
			return err
		}
	}
	return w.WriteLiteral("0")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionAlt010(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription{}, err
	}
	_ = x0
	x1, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionList(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription{}, err
	}
	v.UTRANTDDDescriptionList = x1
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionAlt010(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.UTRANTDDDescriptionList) {
		return fmt.Errorf("edit to field beyond transmitted truncation: UTRANTDDDescriptionList")
	}
	if limit > 1 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescriptionUTRANTDDDescriptionList(w, v.UTRANTDDDescriptionList); err != nil {
			return err
		}
	}
	return nil
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionAlt011(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionAlt011"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("011")
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionAlt011(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("011")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryAlt1(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryAlt1"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("1")
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryAlt1(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("1")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryEUTRANDescription(r *runtime.Reader) (EUTRANDescriptionStruct, error) {
	return decodeEUTRANDescriptionStruct(r)
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryEUTRANDescription(w *runtime.Writer, v EUTRANDescriptionStruct) error {
	return encodeEUTRANDescriptionStruct(w, v)
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryAlt1(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry{}, err
	}
	_ = x0
	x1, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryEUTRANDescription(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry{}, err
	}
	v.EUTRANDescription = x1
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryAlt1(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.EUTRANDescription) {
		return fmt.Errorf("edit to field beyond transmitted truncation: EUTRANDescription")
	}
	if limit > 1 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntryEUTRANDescription(w, v.EUTRANDescription); err != nil {
			return err
		}
	}
	return nil
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionList(r *runtime.Reader) ([]CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry, error) {
	var out []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry
	terminated := false
	for r.Remaining() > 0 {
		if r.Matches("0") {
			if err := r.Expect("0"); err != nil {
				return nil, err
			}
			terminated = true
			break
		}
		before := r.Position()
		v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry(r)
		if err != nil {
			return nil, err
		}
		if r.Position() <= before {
			return nil, r.Error(runtime.Limit, "non-progressing repetition")
		}
		out = append(out, v)
	}
	if !terminated && !r.ZeroExtension() {
		return nil, r.Error(runtime.Truncated, "repetition terminator absent")
	}
	return out, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionList(w *runtime.Writer, v []CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry) error {
	for _, item := range v {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionListEntry(w, item); err != nil {
			return err
		}
	}
	return w.WriteLiteral("0")
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionAlt011(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription{}, err
	}
	_ = x0
	x1, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionList(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription{}, err
	}
	v.EUTRANDescriptionList = x1
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionAlt011(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.EUTRANDescriptionList) {
		return fmt.Errorf("edit to field beyond transmitted truncation: EUTRANDescriptionList")
	}
	if limit > 1 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescriptionEUTRANDescriptionList(w, v.EUTRANDescriptionList); err != nil {
			return err
		}
	}
	return nil
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice, error) {
	var result CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice
	matches := 0
	var chosen *runtime.Reader
	var truncatedErr error
	{
		candidate := r.Fork()
		v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription(candidate)
		if err == nil {
			matches++
			chosen = candidate
			_ = v
			result.Alternative = CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeGSMDescription
			result.GSMDescription = &v
		} else {
			truncatedErr = runtime.PreferTruncation(truncatedErr, err)
		}
	}
	{
		candidate := r.Fork()
		v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription(candidate)
		if err == nil {
			matches++
			chosen = candidate
			_ = v
			result.Alternative = CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeUTRANFDDDescription
			result.UTRANFDDDescription = &v
		} else {
			truncatedErr = runtime.PreferTruncation(truncatedErr, err)
		}
	}
	{
		candidate := r.Fork()
		v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription(candidate)
		if err == nil {
			matches++
			chosen = candidate
			_ = v
			result.Alternative = CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeUTRANTDDDescription
			result.UTRANTDDDescription = &v
		} else {
			truncatedErr = runtime.PreferTruncation(truncatedErr, err)
		}
	}
	{
		candidate := r.Fork()
		v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription(candidate)
		if err == nil {
			matches++
			chosen = candidate
			_ = v
			result.Alternative = CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeEUTRANDescription
			result.EUTRANDescription = &v
		} else {
			truncatedErr = runtime.PreferTruncation(truncatedErr, err)
		}
	}
	if matches == 0 && truncatedErr != nil {
		return result, truncatedErr
	}
	if matches != 1 {
		return result, r.Error(runtime.InvalidBranch, fmt.Sprintf("choice has %d matching alternatives", matches))
	}
	r.Commit(chosen)
	return result, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice) error {
	count := 0
	if v.GSMDescription != nil {
		count++
	}
	if v.UTRANFDDDescription != nil {
		count++
	}
	if v.UTRANTDDDescription != nil {
		count++
	}
	if v.EUTRANDescription != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("choice requires exactly one alternative")
	}
	switch v.Alternative {
	case CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeGSMDescription:
		if v.GSMDescription == nil {
			return fmt.Errorf("choice alternative mismatch")
		}
		return encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceGSMDescription(w, *v.GSMDescription)
	case CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeUTRANFDDDescription:
		if v.UTRANFDDDescription == nil {
			return fmt.Errorf("choice alternative mismatch")
		}
		return encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANFDDDescription(w, *v.UTRANFDDDescription)
	case CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeUTRANTDDDescription:
		if v.UTRANTDDDescription == nil {
			return fmt.Errorf("choice alternative mismatch")
		}
		return encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceUTRANTDDDescription(w, *v.UTRANTDDDescription)
	case CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceAlternativeEUTRANDescription:
		if v.EUTRANDescription == nil {
			return fmt.Errorf("choice alternative mismatch")
		}
		return encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoiceEUTRANDescription(w, *v.EUTRANDescription)
	default:
		return fmt.Errorf("invalid choice alternative")
	}
}
func decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart, error) {
	if err := r.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart"); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart{}, err
	}
	defer r.Leave()
	var v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart
	x0, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice(r)
	if err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart{}, err
	}
	v.GSMDescriptionChoice = x0
	return v, nil
}
func encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart) error {
	if err := w.Enter("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 1
	if n, ok := w.Truncation("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.GSMDescriptionChoice) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GSMDescriptionChoice")
	}
	if limit > 0 {
		if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartGSMDescriptionChoice(w, v.GSMDescriptionChoice); err != nil {
			return err
		}
	}
	return nil
}
func decodeGSMDescriptionStructBandIndicator(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("GSMDescriptionStructBandIndicator"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("Band_Indicator", v)
	return uint8(v), nil
}
func encodeGSMDescriptionStructBandIndicator(w *runtime.Writer, v uint8) error {
	if err := w.Enter("GSMDescriptionStructBandIndicator"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("Band_Indicator", uint64(v))
	return nil
}
func decodeGSMDescriptionStructARFCN(r *runtime.Reader) (uint16, error) {
	if err := r.Enter("GSMDescriptionStructARFCN"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("10")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("ARFCN", v)
	return uint16(v), nil
}
func encodeGSMDescriptionStructARFCN(w *runtime.Writer, v uint16) error {
	if err := w.Enter("GSMDescriptionStructARFCN"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("10")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("ARFCN", uint64(v))
	return nil
}
func decodeGSMDescriptionStructBSIC(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("GSMDescriptionStructBSIC"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("6")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("BSIC", v)
	return uint8(v), nil
}
func encodeGSMDescriptionStructBSIC(w *runtime.Writer, v uint8) error {
	if err := w.Enter("GSMDescriptionStructBSIC"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("6")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("BSIC", uint64(v))
	return nil
}
func decodeGSMDescriptionStruct(r *runtime.Reader) (GSMDescriptionStruct, error) {
	if err := r.Enter("GSMDescriptionStruct"); err != nil {
		return GSMDescriptionStruct{}, err
	}
	defer r.Leave()
	var v GSMDescriptionStruct
	x0, err := decodeGSMDescriptionStructBandIndicator(r)
	if err != nil {
		return GSMDescriptionStruct{}, err
	}
	v.BandIndicator = x0
	x1, err := decodeGSMDescriptionStructARFCN(r)
	if err != nil {
		return GSMDescriptionStruct{}, err
	}
	v.ARFCN = x1
	x2, err := decodeGSMDescriptionStructBSIC(r)
	if err != nil {
		return GSMDescriptionStruct{}, err
	}
	v.BSIC = x2
	return v, nil
}
func encodeGSMDescriptionStruct(w *runtime.Writer, v GSMDescriptionStruct) error {
	if err := w.Enter("GSMDescriptionStruct"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 3
	if n, ok := w.Truncation("GSMDescriptionStruct"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.BandIndicator) {
		return fmt.Errorf("edit to field beyond transmitted truncation: BandIndicator")
	}
	if limit > 0 {
		if err := encodeGSMDescriptionStructBandIndicator(w, v.BandIndicator); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.ARFCN) {
		return fmt.Errorf("edit to field beyond transmitted truncation: ARFCN")
	}
	if limit > 1 {
		if err := encodeGSMDescriptionStructARFCN(w, v.ARFCN); err != nil {
			return err
		}
	}
	if limit <= 2 && !runtime.IsZero(v.BSIC) {
		return fmt.Errorf("edit to field beyond transmitted truncation: BSIC")
	}
	if limit > 2 {
		if err := encodeGSMDescriptionStructBSIC(w, v.BSIC); err != nil {
			return err
		}
	}
	return nil
}
func decodeUTRANFDDDescriptionStructBandwidthFDDValue(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("UTRANFDDDescriptionStructBandwidthFDDValue"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("3")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("Bandwidth_FDD", v)
	return uint8(v), nil
}
func encodeUTRANFDDDescriptionStructBandwidthFDDValue(w *runtime.Writer, v uint8) error {
	if err := w.Enter("UTRANFDDDescriptionStructBandwidthFDDValue"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("3")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("Bandwidth_FDD", uint64(v))
	return nil
}
func decodeUTRANFDDDescriptionStructBandwidthFDDSelector(r *runtime.Reader) (*uint8, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodeUTRANFDDDescriptionStructBandwidthFDDValue(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodeUTRANFDDDescriptionStructBandwidthFDDSelector(w *runtime.Writer, v *uint8) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodeUTRANFDDDescriptionStructBandwidthFDDValue(w, *v)
}
func decodeUTRANFDDDescriptionStructFDDARFCN(r *runtime.Reader) (uint16, error) {
	if err := r.Enter("UTRANFDDDescriptionStructFDDARFCN"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("14")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("FDD-ARFCN", v)
	return uint16(v), nil
}
func encodeUTRANFDDDescriptionStructFDDARFCN(w *runtime.Writer, v uint16) error {
	if err := w.Enter("UTRANFDDDescriptionStructFDDARFCN"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("14")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("FDD-ARFCN", uint64(v))
	return nil
}
func decodeUTRANFDDDescriptionStructFDDIndic0GroupFDDIndic0(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("UTRANFDDDescriptionStructFDDIndic0GroupFDDIndic0"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("FDD_Indic0", v)
	return uint8(v), nil
}
func encodeUTRANFDDDescriptionStructFDDIndic0GroupFDDIndic0(w *runtime.Writer, v uint8) error {
	if err := w.Enter("UTRANFDDDescriptionStructFDDIndic0GroupFDDIndic0"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("FDD_Indic0", uint64(v))
	return nil
}
func decodeUTRANFDDDescriptionStructFDDIndic0GroupNROFFDDCELLS(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("UTRANFDDDescriptionStructFDDIndic0GroupNROFFDDCELLS"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("5")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("NR_OF_FDD_CELLS", v)
	return uint8(v), nil
}
func encodeUTRANFDDDescriptionStructFDDIndic0GroupNROFFDDCELLS(w *runtime.Writer, v uint8) error {
	if err := w.Enter("UTRANFDDDescriptionStructFDDIndic0GroupNROFFDDCELLS"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("5")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("NR_OF_FDD_CELLS", uint64(v))
	return nil
}
func decodeUTRANFDDDescriptionStructFDDIndic0GroupFDDCELLINFORMATIONField(r *runtime.Reader) (runtime.BitString, error) {
	if err := r.Enter("UTRANFDDDescriptionStructFDDIndic0GroupFDDCELLINFORMATIONField"); err != nil {
		return runtime.BitString{}, err
	}
	defer r.Leave()
	width, err := r.Eval("p(NR_OF_FDD_CELLS)")
	if err != nil {
		return runtime.BitString{}, err
	}
	v, err := r.ReadBitString(width)
	if err != nil {
		return runtime.BitString{}, err
	}
	return runtime.BitString(v), nil
}
func encodeUTRANFDDDescriptionStructFDDIndic0GroupFDDCELLINFORMATIONField(w *runtime.Writer, v runtime.BitString) error {
	if err := w.Enter("UTRANFDDDescriptionStructFDDIndic0GroupFDDCELLINFORMATIONField"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("p(NR_OF_FDD_CELLS)")
	if err != nil {
		return err
	}
	if err := w.WriteBitString(v, width); err != nil {
		return err
	}
	return nil
}
func decodeUTRANFDDDescriptionStructFDDIndic0Group(r *runtime.Reader) (UTRANFDDDescriptionStructFDDIndic0Group, error) {
	if err := r.Enter("UTRANFDDDescriptionStructFDDIndic0Group"); err != nil {
		return UTRANFDDDescriptionStructFDDIndic0Group{}, err
	}
	defer r.Leave()
	var v UTRANFDDDescriptionStructFDDIndic0Group
	x0, err := decodeUTRANFDDDescriptionStructFDDIndic0GroupFDDIndic0(r)
	if err != nil {
		return UTRANFDDDescriptionStructFDDIndic0Group{}, err
	}
	v.FDDIndic0 = x0
	x1, err := decodeUTRANFDDDescriptionStructFDDIndic0GroupNROFFDDCELLS(r)
	if err != nil {
		return UTRANFDDDescriptionStructFDDIndic0Group{}, err
	}
	v.NROFFDDCELLS = x1
	x2, err := decodeUTRANFDDDescriptionStructFDDIndic0GroupFDDCELLINFORMATIONField(r)
	if err != nil {
		return UTRANFDDDescriptionStructFDDIndic0Group{}, err
	}
	v.FDDCELLINFORMATIONField = x2
	return v, nil
}
func encodeUTRANFDDDescriptionStructFDDIndic0Group(w *runtime.Writer, v UTRANFDDDescriptionStructFDDIndic0Group) error {
	if err := w.Enter("UTRANFDDDescriptionStructFDDIndic0Group"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 3
	if n, ok := w.Truncation("UTRANFDDDescriptionStructFDDIndic0Group"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.FDDIndic0) {
		return fmt.Errorf("edit to field beyond transmitted truncation: FDDIndic0")
	}
	if limit > 0 {
		if err := encodeUTRANFDDDescriptionStructFDDIndic0GroupFDDIndic0(w, v.FDDIndic0); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.NROFFDDCELLS) {
		return fmt.Errorf("edit to field beyond transmitted truncation: NROFFDDCELLS")
	}
	if limit > 1 {
		if err := encodeUTRANFDDDescriptionStructFDDIndic0GroupNROFFDDCELLS(w, v.NROFFDDCELLS); err != nil {
			return err
		}
	}
	if limit <= 2 && !runtime.IsZero(v.FDDCELLINFORMATIONField) {
		return fmt.Errorf("edit to field beyond transmitted truncation: FDDCELLINFORMATIONField")
	}
	if limit > 2 {
		if err := encodeUTRANFDDDescriptionStructFDDIndic0GroupFDDCELLINFORMATIONField(w, v.FDDCELLINFORMATIONField); err != nil {
			return err
		}
	}
	return nil
}
func decodeUTRANFDDDescriptionStructFDDIndic0GroupSelector(r *runtime.Reader) (*UTRANFDDDescriptionStructFDDIndic0Group, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodeUTRANFDDDescriptionStructFDDIndic0Group(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodeUTRANFDDDescriptionStructFDDIndic0GroupSelector(w *runtime.Writer, v *UTRANFDDDescriptionStructFDDIndic0Group) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodeUTRANFDDDescriptionStructFDDIndic0Group(w, *v)
}
func decodeUTRANFDDDescriptionStruct(r *runtime.Reader) (UTRANFDDDescriptionStruct, error) {
	if err := r.Enter("UTRANFDDDescriptionStruct"); err != nil {
		return UTRANFDDDescriptionStruct{}, err
	}
	defer r.Leave()
	var v UTRANFDDDescriptionStruct
	x0, err := decodeUTRANFDDDescriptionStructBandwidthFDDSelector(r)
	if err != nil {
		return UTRANFDDDescriptionStruct{}, err
	}
	v.BandwidthFDD = x0
	x1, err := decodeUTRANFDDDescriptionStructFDDARFCN(r)
	if err != nil {
		return UTRANFDDDescriptionStruct{}, err
	}
	v.FDDARFCN = x1
	x2, err := decodeUTRANFDDDescriptionStructFDDIndic0GroupSelector(r)
	if err != nil {
		return UTRANFDDDescriptionStruct{}, err
	}
	v.FDDIndic0Group = x2
	return v, nil
}
func encodeUTRANFDDDescriptionStruct(w *runtime.Writer, v UTRANFDDDescriptionStruct) error {
	if err := w.Enter("UTRANFDDDescriptionStruct"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 3
	if n, ok := w.Truncation("UTRANFDDDescriptionStruct"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.BandwidthFDD) {
		return fmt.Errorf("edit to field beyond transmitted truncation: BandwidthFDD")
	}
	if limit > 0 {
		if err := encodeUTRANFDDDescriptionStructBandwidthFDDSelector(w, v.BandwidthFDD); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.FDDARFCN) {
		return fmt.Errorf("edit to field beyond transmitted truncation: FDDARFCN")
	}
	if limit > 1 {
		if err := encodeUTRANFDDDescriptionStructFDDARFCN(w, v.FDDARFCN); err != nil {
			return err
		}
	}
	if limit <= 2 && !runtime.IsZero(v.FDDIndic0Group) {
		return fmt.Errorf("edit to field beyond transmitted truncation: FDDIndic0Group")
	}
	if limit > 2 {
		if err := encodeUTRANFDDDescriptionStructFDDIndic0GroupSelector(w, v.FDDIndic0Group); err != nil {
			return err
		}
	}
	return nil
}
func decodeUTRANTDDDescriptionStructBandwidthTDDValue(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("UTRANTDDDescriptionStructBandwidthTDDValue"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("3")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("Bandwidth_TDD", v)
	return uint8(v), nil
}
func encodeUTRANTDDDescriptionStructBandwidthTDDValue(w *runtime.Writer, v uint8) error {
	if err := w.Enter("UTRANTDDDescriptionStructBandwidthTDDValue"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("3")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("Bandwidth_TDD", uint64(v))
	return nil
}
func decodeUTRANTDDDescriptionStructBandwidthTDDSelector(r *runtime.Reader) (*uint8, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodeUTRANTDDDescriptionStructBandwidthTDDValue(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodeUTRANTDDDescriptionStructBandwidthTDDSelector(w *runtime.Writer, v *uint8) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodeUTRANTDDDescriptionStructBandwidthTDDValue(w, *v)
}
func decodeUTRANTDDDescriptionStructTDDARFCN(r *runtime.Reader) (uint16, error) {
	if err := r.Enter("UTRANTDDDescriptionStructTDDARFCN"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("14")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("TDD-ARFCN", v)
	return uint16(v), nil
}
func encodeUTRANTDDDescriptionStructTDDARFCN(w *runtime.Writer, v uint16) error {
	if err := w.Enter("UTRANTDDDescriptionStructTDDARFCN"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("14")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("TDD-ARFCN", uint64(v))
	return nil
}
func decodeUTRANTDDDescriptionStructTDDIndic0GroupTDDIndic0(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("UTRANTDDDescriptionStructTDDIndic0GroupTDDIndic0"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("TDD_Indic0", v)
	return uint8(v), nil
}
func encodeUTRANTDDDescriptionStructTDDIndic0GroupTDDIndic0(w *runtime.Writer, v uint8) error {
	if err := w.Enter("UTRANTDDDescriptionStructTDDIndic0GroupTDDIndic0"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("TDD_Indic0", uint64(v))
	return nil
}
func decodeUTRANTDDDescriptionStructTDDIndic0GroupNROFTDDCELLS(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("UTRANTDDDescriptionStructTDDIndic0GroupNROFTDDCELLS"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("5")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("NR_OF_TDD_CELLS", v)
	return uint8(v), nil
}
func encodeUTRANTDDDescriptionStructTDDIndic0GroupNROFTDDCELLS(w *runtime.Writer, v uint8) error {
	if err := w.Enter("UTRANTDDDescriptionStructTDDIndic0GroupNROFTDDCELLS"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("5")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("NR_OF_TDD_CELLS", uint64(v))
	return nil
}
func decodeUTRANTDDDescriptionStructTDDIndic0GroupTDDCELLINFORMATIONField(r *runtime.Reader) (runtime.BitString, error) {
	if err := r.Enter("UTRANTDDDescriptionStructTDDIndic0GroupTDDCELLINFORMATIONField"); err != nil {
		return runtime.BitString{}, err
	}
	defer r.Leave()
	width, err := r.Eval("q(NR_OF_TDD_CELLS)")
	if err != nil {
		return runtime.BitString{}, err
	}
	v, err := r.ReadBitString(width)
	if err != nil {
		return runtime.BitString{}, err
	}
	return runtime.BitString(v), nil
}
func encodeUTRANTDDDescriptionStructTDDIndic0GroupTDDCELLINFORMATIONField(w *runtime.Writer, v runtime.BitString) error {
	if err := w.Enter("UTRANTDDDescriptionStructTDDIndic0GroupTDDCELLINFORMATIONField"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("q(NR_OF_TDD_CELLS)")
	if err != nil {
		return err
	}
	if err := w.WriteBitString(v, width); err != nil {
		return err
	}
	return nil
}
func decodeUTRANTDDDescriptionStructTDDIndic0Group(r *runtime.Reader) (UTRANTDDDescriptionStructTDDIndic0Group, error) {
	if err := r.Enter("UTRANTDDDescriptionStructTDDIndic0Group"); err != nil {
		return UTRANTDDDescriptionStructTDDIndic0Group{}, err
	}
	defer r.Leave()
	var v UTRANTDDDescriptionStructTDDIndic0Group
	x0, err := decodeUTRANTDDDescriptionStructTDDIndic0GroupTDDIndic0(r)
	if err != nil {
		return UTRANTDDDescriptionStructTDDIndic0Group{}, err
	}
	v.TDDIndic0 = x0
	x1, err := decodeUTRANTDDDescriptionStructTDDIndic0GroupNROFTDDCELLS(r)
	if err != nil {
		return UTRANTDDDescriptionStructTDDIndic0Group{}, err
	}
	v.NROFTDDCELLS = x1
	x2, err := decodeUTRANTDDDescriptionStructTDDIndic0GroupTDDCELLINFORMATIONField(r)
	if err != nil {
		return UTRANTDDDescriptionStructTDDIndic0Group{}, err
	}
	v.TDDCELLINFORMATIONField = x2
	return v, nil
}
func encodeUTRANTDDDescriptionStructTDDIndic0Group(w *runtime.Writer, v UTRANTDDDescriptionStructTDDIndic0Group) error {
	if err := w.Enter("UTRANTDDDescriptionStructTDDIndic0Group"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 3
	if n, ok := w.Truncation("UTRANTDDDescriptionStructTDDIndic0Group"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.TDDIndic0) {
		return fmt.Errorf("edit to field beyond transmitted truncation: TDDIndic0")
	}
	if limit > 0 {
		if err := encodeUTRANTDDDescriptionStructTDDIndic0GroupTDDIndic0(w, v.TDDIndic0); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.NROFTDDCELLS) {
		return fmt.Errorf("edit to field beyond transmitted truncation: NROFTDDCELLS")
	}
	if limit > 1 {
		if err := encodeUTRANTDDDescriptionStructTDDIndic0GroupNROFTDDCELLS(w, v.NROFTDDCELLS); err != nil {
			return err
		}
	}
	if limit <= 2 && !runtime.IsZero(v.TDDCELLINFORMATIONField) {
		return fmt.Errorf("edit to field beyond transmitted truncation: TDDCELLINFORMATIONField")
	}
	if limit > 2 {
		if err := encodeUTRANTDDDescriptionStructTDDIndic0GroupTDDCELLINFORMATIONField(w, v.TDDCELLINFORMATIONField); err != nil {
			return err
		}
	}
	return nil
}
func decodeUTRANTDDDescriptionStructTDDIndic0GroupSelector(r *runtime.Reader) (*UTRANTDDDescriptionStructTDDIndic0Group, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodeUTRANTDDDescriptionStructTDDIndic0Group(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodeUTRANTDDDescriptionStructTDDIndic0GroupSelector(w *runtime.Writer, v *UTRANTDDDescriptionStructTDDIndic0Group) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodeUTRANTDDDescriptionStructTDDIndic0Group(w, *v)
}
func decodeUTRANTDDDescriptionStruct(r *runtime.Reader) (UTRANTDDDescriptionStruct, error) {
	if err := r.Enter("UTRANTDDDescriptionStruct"); err != nil {
		return UTRANTDDDescriptionStruct{}, err
	}
	defer r.Leave()
	var v UTRANTDDDescriptionStruct
	x0, err := decodeUTRANTDDDescriptionStructBandwidthTDDSelector(r)
	if err != nil {
		return UTRANTDDDescriptionStruct{}, err
	}
	v.BandwidthTDD = x0
	x1, err := decodeUTRANTDDDescriptionStructTDDARFCN(r)
	if err != nil {
		return UTRANTDDDescriptionStruct{}, err
	}
	v.TDDARFCN = x1
	x2, err := decodeUTRANTDDDescriptionStructTDDIndic0GroupSelector(r)
	if err != nil {
		return UTRANTDDDescriptionStruct{}, err
	}
	v.TDDIndic0Group = x2
	return v, nil
}
func encodeUTRANTDDDescriptionStruct(w *runtime.Writer, v UTRANTDDDescriptionStruct) error {
	if err := w.Enter("UTRANTDDDescriptionStruct"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 3
	if n, ok := w.Truncation("UTRANTDDDescriptionStruct"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.BandwidthTDD) {
		return fmt.Errorf("edit to field beyond transmitted truncation: BandwidthTDD")
	}
	if limit > 0 {
		if err := encodeUTRANTDDDescriptionStructBandwidthTDDSelector(w, v.BandwidthTDD); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.TDDARFCN) {
		return fmt.Errorf("edit to field beyond transmitted truncation: TDDARFCN")
	}
	if limit > 1 {
		if err := encodeUTRANTDDDescriptionStructTDDARFCN(w, v.TDDARFCN); err != nil {
			return err
		}
	}
	if limit <= 2 && !runtime.IsZero(v.TDDIndic0Group) {
		return fmt.Errorf("edit to field beyond transmitted truncation: TDDIndic0Group")
	}
	if limit > 2 {
		if err := encodeUTRANTDDDescriptionStructTDDIndic0GroupSelector(w, v.TDDIndic0Group); err != nil {
			return err
		}
	}
	return nil
}
func decodeEUTRANDescriptionStructEARFCN(r *runtime.Reader) (uint16, error) {
	if err := r.Enter("EUTRANDescriptionStructEARFCN"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("16")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("EARFCN", v)
	return uint16(v), nil
}
func encodeEUTRANDescriptionStructEARFCN(w *runtime.Writer, v uint16) error {
	if err := w.Enter("EUTRANDescriptionStructEARFCN"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("16")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("EARFCN", uint64(v))
	return nil
}
func decodeEUTRANDescriptionStructMeasurementBandwidthValue(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("EUTRANDescriptionStructMeasurementBandwidthValue"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("3")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("Measurement Bandwidth", v)
	return uint8(v), nil
}
func encodeEUTRANDescriptionStructMeasurementBandwidthValue(w *runtime.Writer, v uint8) error {
	if err := w.Enter("EUTRANDescriptionStructMeasurementBandwidthValue"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("3")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("Measurement Bandwidth", uint64(v))
	return nil
}
func decodeEUTRANDescriptionStructMeasurementBandwidthSelector(r *runtime.Reader) (*uint8, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodeEUTRANDescriptionStructMeasurementBandwidthValue(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodeEUTRANDescriptionStructMeasurementBandwidthSelector(w *runtime.Writer, v *uint8) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodeEUTRANDescriptionStructMeasurementBandwidthValue(w, *v)
}
func decodeEUTRANDescriptionStructNotAllowedCellsValue(r *runtime.Reader) (ies.PCIDGroupIE, error) {
	return ies.DecodePCIDGroupIEFrom(r)
}
func encodeEUTRANDescriptionStructNotAllowedCellsValue(w *runtime.Writer, v ies.PCIDGroupIE) error {
	return ies.EncodePCIDGroupIETo(w, v)
}
func decodeEUTRANDescriptionStructNotAllowedCellsSelector(r *runtime.Reader) (*ies.PCIDGroupIE, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodeEUTRANDescriptionStructNotAllowedCellsValue(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodeEUTRANDescriptionStructNotAllowedCellsSelector(w *runtime.Writer, v *ies.PCIDGroupIE) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodeEUTRANDescriptionStructNotAllowedCellsValue(w, *v)
}
func decodeEUTRANDescriptionStructTARGETPCIDValue(r *runtime.Reader) (uint16, error) {
	if err := r.Enter("EUTRANDescriptionStructTARGETPCIDValue"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("9")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("TARGET_PCID", v)
	return uint16(v), nil
}
func encodeEUTRANDescriptionStructTARGETPCIDValue(w *runtime.Writer, v uint16) error {
	if err := w.Enter("EUTRANDescriptionStructTARGETPCIDValue"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("9")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("TARGET_PCID", uint64(v))
	return nil
}
func decodeEUTRANDescriptionStructTARGETPCIDSelector(r *runtime.Reader) (*uint16, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodeEUTRANDescriptionStructTARGETPCIDValue(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodeEUTRANDescriptionStructTARGETPCIDSelector(w *runtime.Writer, v *uint16) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodeEUTRANDescriptionStructTARGETPCIDValue(w, *v)
}
func decodeEUTRANDescriptionStruct(r *runtime.Reader) (EUTRANDescriptionStruct, error) {
	if err := r.Enter("EUTRANDescriptionStruct"); err != nil {
		return EUTRANDescriptionStruct{}, err
	}
	defer r.Leave()
	var v EUTRANDescriptionStruct
	x0, err := decodeEUTRANDescriptionStructEARFCN(r)
	if err != nil {
		return EUTRANDescriptionStruct{}, err
	}
	v.EARFCN = x0
	x1, err := decodeEUTRANDescriptionStructMeasurementBandwidthSelector(r)
	if err != nil {
		return EUTRANDescriptionStruct{}, err
	}
	v.MeasurementBandwidth = x1
	x2, err := decodeEUTRANDescriptionStructNotAllowedCellsSelector(r)
	if err != nil {
		return EUTRANDescriptionStruct{}, err
	}
	v.NotAllowedCells = x2
	x3, err := decodeEUTRANDescriptionStructTARGETPCIDSelector(r)
	if err != nil {
		return EUTRANDescriptionStruct{}, err
	}
	v.TARGETPCID = x3
	return v, nil
}
func encodeEUTRANDescriptionStruct(w *runtime.Writer, v EUTRANDescriptionStruct) error {
	if err := w.Enter("EUTRANDescriptionStruct"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 4
	if n, ok := w.Truncation("EUTRANDescriptionStruct"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.EARFCN) {
		return fmt.Errorf("edit to field beyond transmitted truncation: EARFCN")
	}
	if limit > 0 {
		if err := encodeEUTRANDescriptionStructEARFCN(w, v.EARFCN); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.MeasurementBandwidth) {
		return fmt.Errorf("edit to field beyond transmitted truncation: MeasurementBandwidth")
	}
	if limit > 1 {
		if err := encodeEUTRANDescriptionStructMeasurementBandwidthSelector(w, v.MeasurementBandwidth); err != nil {
			return err
		}
	}
	if limit <= 2 && !runtime.IsZero(v.NotAllowedCells) {
		return fmt.Errorf("edit to field beyond transmitted truncation: NotAllowedCells")
	}
	if limit > 2 {
		if err := encodeEUTRANDescriptionStructNotAllowedCellsSelector(w, v.NotAllowedCells); err != nil {
			return err
		}
	}
	if limit <= 3 && !runtime.IsZero(v.TARGETPCID) {
		return fmt.Errorf("edit to field beyond transmitted truncation: TARGETPCID")
	}
	if limit > 3 {
		if err := encodeEUTRANDescriptionStructTARGETPCIDSelector(w, v.TARGETPCID); err != nil {
			return err
		}
	}
	return nil
}

// DecodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart decodes TS 44.018 V19.0.0 §10.5.2.1e <Cell Selection Indicator after release of all TCH and SDCCH value part>.
func DecodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartFrom(r *runtime.Reader) (CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart, error) {
	if err := r.Check(); err != nil {
		return CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart{}, err
	}
	return decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(r)
}
func EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartTo(w *runtime.Writer, v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart) error {
	return encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(w, v)
}
func DecodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(data []byte) (runtime.Decoded[CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart]{}, err
	}
	if len(data) < 2 {
		return runtime.Decoded[CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart]{}, &runtime.DecodeError{Kind: runtime.Truncated, Offset: runtime.InputBits(data), Detail: "CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart requires at least 16 bits"}
	}
	input := data
	r := runtime.NewReader(input)
	r.SetZeroExtension(false)
	v, err := decodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(r)
	if err != nil {
		return runtime.Decoded[CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart encodes an edited or newly constructed value through direct bit operations.
func EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(false)
	if err := encodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(w, v); err != nil {
		return nil, err
	}
	if err := w.PadMinimum(16, false); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	if len(out) < 2 {
		return nil, fmt.Errorf("CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart requires at least 16 bits")
	}
	return out, nil
}

// EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartCanonical(v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart) ([]byte, error) {
	return runtime.CanonicalEncode(v, 2, 0, false, EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart, DecodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart, nil)
}

// EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartCanonicalAtLength(v CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 2, 0, EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart, DecodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart, nil)
}

// DecodeGSMDescriptionStruct decodes TS 44.018 V19.0.0 §10.5.2.1e <GSM Description struct>.
func DecodeGSMDescriptionStructFrom(r *runtime.Reader) (GSMDescriptionStruct, error) {
	if err := r.Check(); err != nil {
		return GSMDescriptionStruct{}, err
	}
	return decodeGSMDescriptionStruct(r)
}
func EncodeGSMDescriptionStructTo(w *runtime.Writer, v GSMDescriptionStruct) error {
	return encodeGSMDescriptionStruct(w, v)
}
func DecodeGSMDescriptionStruct(data []byte) (runtime.Decoded[GSMDescriptionStruct], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[GSMDescriptionStruct]{}, err
	}
	input := data
	r := runtime.NewReader(input)
	r.SetZeroExtension(false)
	v, err := decodeGSMDescriptionStruct(r)
	if err != nil {
		return runtime.Decoded[GSMDescriptionStruct]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[GSMDescriptionStruct]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeGSMDescriptionStruct encodes an edited or newly constructed value through direct bit operations.
func EncodeGSMDescriptionStruct(v GSMDescriptionStruct) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(false)
	if err := encodeGSMDescriptionStruct(w, v); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Canonical maximum: TS 44.018 V19.0.0 §10.5.2.1e (finite maximum from the printed CSN.1 grammar).
// EncodeGSMDescriptionStructCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeGSMDescriptionStructCanonical(v GSMDescriptionStruct) ([]byte, error) {
	return runtime.CanonicalEncode(v, 0, 3, false, EncodeGSMDescriptionStruct, DecodeGSMDescriptionStruct, nil)
}

// EncodeGSMDescriptionStructCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeGSMDescriptionStructCanonicalAtLength(v GSMDescriptionStruct, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 0, 3, EncodeGSMDescriptionStruct, DecodeGSMDescriptionStruct, nil)
}

// DecodeUTRANFDDDescriptionStruct decodes TS 44.018 V19.0.0 §10.5.2.1e <UTRAN FDD Description struct>.
func DecodeUTRANFDDDescriptionStructFrom(r *runtime.Reader) (UTRANFDDDescriptionStruct, error) {
	if err := r.Check(); err != nil {
		return UTRANFDDDescriptionStruct{}, err
	}
	return decodeUTRANFDDDescriptionStruct(r)
}
func EncodeUTRANFDDDescriptionStructTo(w *runtime.Writer, v UTRANFDDDescriptionStruct) error {
	return encodeUTRANFDDDescriptionStruct(w, v)
}
func DecodeUTRANFDDDescriptionStruct(data []byte) (runtime.Decoded[UTRANFDDDescriptionStruct], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[UTRANFDDDescriptionStruct]{}, err
	}
	input := data
	r := runtime.NewReader(input)
	r.SetZeroExtension(false)
	v, err := decodeUTRANFDDDescriptionStruct(r)
	if err != nil {
		return runtime.Decoded[UTRANFDDDescriptionStruct]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[UTRANFDDDescriptionStruct]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeUTRANFDDDescriptionStruct encodes an edited or newly constructed value through direct bit operations.
func EncodeUTRANFDDDescriptionStruct(v UTRANFDDDescriptionStruct) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(false)
	if err := encodeUTRANFDDDescriptionStruct(w, v); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeUTRANFDDDescriptionStructCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeUTRANFDDDescriptionStructCanonical(v UTRANFDDDescriptionStruct) ([]byte, error) {
	return runtime.CanonicalEncode(v, 0, 0, false, EncodeUTRANFDDDescriptionStruct, DecodeUTRANFDDDescriptionStruct, nil)
}

// EncodeUTRANFDDDescriptionStructCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeUTRANFDDDescriptionStructCanonicalAtLength(v UTRANFDDDescriptionStruct, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 0, 0, EncodeUTRANFDDDescriptionStruct, DecodeUTRANFDDDescriptionStruct, nil)
}

// DecodeUTRANTDDDescriptionStruct decodes TS 44.018 V19.0.0 §10.5.2.1e <UTRAN TDD Description struct>.
func DecodeUTRANTDDDescriptionStructFrom(r *runtime.Reader) (UTRANTDDDescriptionStruct, error) {
	if err := r.Check(); err != nil {
		return UTRANTDDDescriptionStruct{}, err
	}
	return decodeUTRANTDDDescriptionStruct(r)
}
func EncodeUTRANTDDDescriptionStructTo(w *runtime.Writer, v UTRANTDDDescriptionStruct) error {
	return encodeUTRANTDDDescriptionStruct(w, v)
}
func DecodeUTRANTDDDescriptionStruct(data []byte) (runtime.Decoded[UTRANTDDDescriptionStruct], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[UTRANTDDDescriptionStruct]{}, err
	}
	input := data
	r := runtime.NewReader(input)
	r.SetZeroExtension(false)
	v, err := decodeUTRANTDDDescriptionStruct(r)
	if err != nil {
		return runtime.Decoded[UTRANTDDDescriptionStruct]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[UTRANTDDDescriptionStruct]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeUTRANTDDDescriptionStruct encodes an edited or newly constructed value through direct bit operations.
func EncodeUTRANTDDDescriptionStruct(v UTRANTDDDescriptionStruct) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(false)
	if err := encodeUTRANTDDDescriptionStruct(w, v); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeUTRANTDDDescriptionStructCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeUTRANTDDDescriptionStructCanonical(v UTRANTDDDescriptionStruct) ([]byte, error) {
	return runtime.CanonicalEncode(v, 0, 0, false, EncodeUTRANTDDDescriptionStruct, DecodeUTRANTDDDescriptionStruct, nil)
}

// EncodeUTRANTDDDescriptionStructCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeUTRANTDDDescriptionStructCanonicalAtLength(v UTRANTDDDescriptionStruct, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 0, 0, EncodeUTRANTDDDescriptionStruct, DecodeUTRANTDDDescriptionStruct, nil)
}

// DecodeEUTRANDescriptionStruct decodes TS 44.018 V19.0.0 §10.5.2.1e <E-UTRAN Description struct>.
func DecodeEUTRANDescriptionStructFrom(r *runtime.Reader) (EUTRANDescriptionStruct, error) {
	if err := r.Check(); err != nil {
		return EUTRANDescriptionStruct{}, err
	}
	return decodeEUTRANDescriptionStruct(r)
}
func EncodeEUTRANDescriptionStructTo(w *runtime.Writer, v EUTRANDescriptionStruct) error {
	return encodeEUTRANDescriptionStruct(w, v)
}
func DecodeEUTRANDescriptionStruct(data []byte) (runtime.Decoded[EUTRANDescriptionStruct], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[EUTRANDescriptionStruct]{}, err
	}
	input := data
	r := runtime.NewReader(input)
	r.SetZeroExtension(false)
	v, err := decodeEUTRANDescriptionStruct(r)
	if err != nil {
		return runtime.Decoded[EUTRANDescriptionStruct]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[EUTRANDescriptionStruct]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeEUTRANDescriptionStruct encodes an edited or newly constructed value through direct bit operations.
func EncodeEUTRANDescriptionStruct(v EUTRANDescriptionStruct) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(false)
	if err := encodeEUTRANDescriptionStruct(w, v); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeEUTRANDescriptionStructCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeEUTRANDescriptionStructCanonical(v EUTRANDescriptionStruct) ([]byte, error) {
	return runtime.CanonicalEncode(v, 0, 0, false, EncodeEUTRANDescriptionStruct, DecodeEUTRANDescriptionStruct, nil)
}

// EncodeEUTRANDescriptionStructCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeEUTRANDescriptionStructCanonicalAtLength(v EUTRANDescriptionStruct, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 0, 0, EncodeEUTRANDescriptionStruct, DecodeEUTRANDescriptionStruct, nil)
}
func Definitions() []string {
	return []string{"Cell Selection Indicator after release of all TCH and SDCCH value part", "GSM Description struct", "UTRAN FDD Description struct", "UTRAN TDD Description struct", "E-UTRAN Description struct"}
}
func Descriptors() []runtime.Descriptor {
	return []runtime.Descriptor{
		{Standard: "TS 44.018", Version: "19.0.0", Clause: "10.5.2.1e", Name: "Cell Selection Indicator after release of all TCH and SDCCH value part", MaxOctets: 0, Decode: func(data []byte) (any, error) {
			return DecodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(data)
		}, DecodeFrom: func(r *runtime.Reader) (any, error) {
			return DecodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartFrom(r)
		}, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart:
				return EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(v)
			case runtime.Decoded[CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart]:
				return EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart:
				return EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartCanonical(v)
			case runtime.Decoded[CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart]:
				return EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart:
				return EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartCanonicalAtLength(v, octets)
			case runtime.Decoded[CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart]:
				return EncodeCellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePartCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for CellSelectionIndicatorAfterReleaseOfAllTCHAndSDCCHValuePart")
			}
		}},
		{Standard: "TS 44.018", Version: "19.0.0", Clause: "10.5.2.1e", Name: "GSM Description struct", MaxOctets: 3, Decode: func(data []byte) (any, error) { return DecodeGSMDescriptionStruct(data) }, DecodeFrom: func(r *runtime.Reader) (any, error) { return DecodeGSMDescriptionStructFrom(r) }, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case GSMDescriptionStruct:
				return EncodeGSMDescriptionStruct(v)
			case runtime.Decoded[GSMDescriptionStruct]:
				return EncodeGSMDescriptionStruct(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for GSMDescriptionStruct")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case GSMDescriptionStruct:
				return EncodeGSMDescriptionStructCanonical(v)
			case runtime.Decoded[GSMDescriptionStruct]:
				return EncodeGSMDescriptionStructCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for GSMDescriptionStruct")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case GSMDescriptionStruct:
				return EncodeGSMDescriptionStructCanonicalAtLength(v, octets)
			case runtime.Decoded[GSMDescriptionStruct]:
				return EncodeGSMDescriptionStructCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for GSMDescriptionStruct")
			}
		}},
		{Standard: "TS 44.018", Version: "19.0.0", Clause: "10.5.2.1e", Name: "UTRAN FDD Description struct", MaxOctets: 0, Decode: func(data []byte) (any, error) { return DecodeUTRANFDDDescriptionStruct(data) }, DecodeFrom: func(r *runtime.Reader) (any, error) { return DecodeUTRANFDDDescriptionStructFrom(r) }, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case UTRANFDDDescriptionStruct:
				return EncodeUTRANFDDDescriptionStruct(v)
			case runtime.Decoded[UTRANFDDDescriptionStruct]:
				return EncodeUTRANFDDDescriptionStruct(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for UTRANFDDDescriptionStruct")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case UTRANFDDDescriptionStruct:
				return EncodeUTRANFDDDescriptionStructCanonical(v)
			case runtime.Decoded[UTRANFDDDescriptionStruct]:
				return EncodeUTRANFDDDescriptionStructCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for UTRANFDDDescriptionStruct")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case UTRANFDDDescriptionStruct:
				return EncodeUTRANFDDDescriptionStructCanonicalAtLength(v, octets)
			case runtime.Decoded[UTRANFDDDescriptionStruct]:
				return EncodeUTRANFDDDescriptionStructCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for UTRANFDDDescriptionStruct")
			}
		}},
		{Standard: "TS 44.018", Version: "19.0.0", Clause: "10.5.2.1e", Name: "UTRAN TDD Description struct", MaxOctets: 0, Decode: func(data []byte) (any, error) { return DecodeUTRANTDDDescriptionStruct(data) }, DecodeFrom: func(r *runtime.Reader) (any, error) { return DecodeUTRANTDDDescriptionStructFrom(r) }, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case UTRANTDDDescriptionStruct:
				return EncodeUTRANTDDDescriptionStruct(v)
			case runtime.Decoded[UTRANTDDDescriptionStruct]:
				return EncodeUTRANTDDDescriptionStruct(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for UTRANTDDDescriptionStruct")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case UTRANTDDDescriptionStruct:
				return EncodeUTRANTDDDescriptionStructCanonical(v)
			case runtime.Decoded[UTRANTDDDescriptionStruct]:
				return EncodeUTRANTDDDescriptionStructCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for UTRANTDDDescriptionStruct")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case UTRANTDDDescriptionStruct:
				return EncodeUTRANTDDDescriptionStructCanonicalAtLength(v, octets)
			case runtime.Decoded[UTRANTDDDescriptionStruct]:
				return EncodeUTRANTDDDescriptionStructCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for UTRANTDDDescriptionStruct")
			}
		}},
		{Standard: "TS 44.018", Version: "19.0.0", Clause: "10.5.2.1e", Name: "E-UTRAN Description struct", MaxOctets: 0, Decode: func(data []byte) (any, error) { return DecodeEUTRANDescriptionStruct(data) }, DecodeFrom: func(r *runtime.Reader) (any, error) { return DecodeEUTRANDescriptionStructFrom(r) }, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case EUTRANDescriptionStruct:
				return EncodeEUTRANDescriptionStruct(v)
			case runtime.Decoded[EUTRANDescriptionStruct]:
				return EncodeEUTRANDescriptionStruct(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for EUTRANDescriptionStruct")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case EUTRANDescriptionStruct:
				return EncodeEUTRANDescriptionStructCanonical(v)
			case runtime.Decoded[EUTRANDescriptionStruct]:
				return EncodeEUTRANDescriptionStructCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for EUTRANDescriptionStruct")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case EUTRANDescriptionStruct:
				return EncodeEUTRANDescriptionStructCanonicalAtLength(v, octets)
			case runtime.Decoded[EUTRANDescriptionStruct]:
				return EncodeEUTRANDescriptionStructCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for EUTRANDescriptionStruct")
			}
		}},
	}
}
func Lookup(name string) (runtime.Descriptor, error) {
	var matches []runtime.Descriptor
	for _, d := range Descriptors() {
		if d.Name == name {
			matches = append(matches, d)
		}
	}
	if len(matches) == 1 {
		return matches[0], nil
	}
	if len(matches) == 0 {
		return runtime.Descriptor{}, fmt.Errorf("unknown CSN.1 definition %q", name)
	}
	var clauses []string
	for _, d := range matches {
		clauses = append(clauses, d.Clause)
	}
	return runtime.Descriptor{}, fmt.Errorf("ambiguous CSN.1 definition %q in clauses %v", name, clauses)
}
func LookupClause(clause, name string) (runtime.Descriptor, error) {
	for _, d := range Descriptors() {
		if d.Clause == clause && d.Name == name {
			return d, nil
		}
	}
	return runtime.Descriptor{}, fmt.Errorf("unknown CSN.1 definition %q in clause %s", name, clause)
}
