// Code generated by csn1c from TS 24.008 V20.1.0 §10.5.5.12; DO NOT EDIT.
// Extracted source SHA-256: 392a04d15b185c121a081e3a88b20d2831c87a96a7625a920bcab4d8edd8ce34.
// Package msnetcap contains typed CSN.1 codecs. Plain Encode calls preserve received layout and fail if an edit changes its semantic boundary. Encode<Type>Canonical copies the value, discards received layout, and checks that fresh encoding decodes to equivalent typed fields within a source-defined maximum. Definitions without a standalone maximum require Encode<Type>CanonicalAtLength with the containing value length; the default fails with runtime.ExtentError.
package msnetcap

import (
	"fmt"
	"github.com/gomaja/go-csn1/runtime"
)

type MSNetworkCapabilityValuePart struct {
	GEA1Bits                                      GEA1Bits
	SMCapabilitiesViaDedicatedChannels            uint8
	SMCapabilitiesViaGPRSChannels                 uint8
	UCS2Support                                   uint8
	SSScreeningIndicator                          uint8
	SoLSACapability                               uint8
	RevisionLevelIndicator                        uint8
	PFCFeatureMode                                uint8
	ExtendedGEABits                               ExtendedGEABits
	LCSVACapability                               uint8
	PSInterRATHOFromGERANToUTRANIuModeCapability  uint8
	PSInterRATHOFromGERANToEUTRANS1ModeCapability uint8
	EMMCombinedProceduresCapability               uint8
	ISRSupport                                    uint8
	SRVCCToGERANUTRANCapability                   uint8
	EPCCapability                                 uint8
	NFCapability                                  uint8
	GERANNetworkSharingCapability                 uint8
	UserPlaneIntegrityProtectionSupport           uint8
	GIA4                                          uint8
	GIA5                                          uint8
	GIA6                                          uint8
	GIA7                                          uint8
	EPCOIEIndicator                               uint8
	RestrictionOnUseOfEnhancedCoverageCapability  uint8
	DualConnectivityOfEUTRAWithNRCapability       uint8
	Wire                                          runtime.WireInfo `json:"-"`
}
type GEA1Bits struct {
	GEA1 uint8
	Wire runtime.WireInfo `json:"-"`
}
type ExtendedGEABits struct {
	GEA2 uint8
	GEA3 uint8
	GEA4 uint8
	GEA5 uint8
	GEA6 uint8
	GEA7 uint8
	Wire runtime.WireInfo `json:"-"`
}
type SpareBitsAlternativesAltUnlabeledVariant2 struct {
}
type SpareBitsAlternativesAlternative uint8

const (
	SpareBitsAlternativesAlternativeAltUnlabeled         SpareBitsAlternativesAlternative = iota
	SpareBitsAlternativesAlternativeAltUnlabeledVariant2 SpareBitsAlternativesAlternative = iota
)

type SpareBitsAlternatives struct {
	Alternative          SpareBitsAlternativesAlternative
	AltUnlabeled         *struct{}
	AltUnlabeledVariant2 *SpareBitsAlternativesAltUnlabeledVariant2
}
type SpareBits struct {
	Alternatives SpareBitsAlternatives
	Wire         runtime.WireInfo `json:"-"`
}

func decodeMSNetworkCapabilityValuePartGEA1Bits(r *runtime.Reader) (GEA1Bits, error) {
	return decodeGEA1Bits(r)
}
func encodeMSNetworkCapabilityValuePartGEA1Bits(w *runtime.Writer, v GEA1Bits) error {
	return encodeGEA1Bits(w, v)
}
func decodeMSNetworkCapabilityValuePartSMCapabilitiesViaDedicatedChannels(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartSMCapabilitiesViaDedicatedChannels"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("SM capabilities via dedicated channels", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartSMCapabilitiesViaDedicatedChannels(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartSMCapabilitiesViaDedicatedChannels"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("SM capabilities via dedicated channels", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartSMCapabilitiesViaGPRSChannels(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartSMCapabilitiesViaGPRSChannels"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("SM capabilities via GPRS channels", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartSMCapabilitiesViaGPRSChannels(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartSMCapabilitiesViaGPRSChannels"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("SM capabilities via GPRS channels", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartUCS2Support(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartUCS2Support"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("UCS2 support", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartUCS2Support(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartUCS2Support"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("UCS2 support", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartSSScreeningIndicator(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartSSScreeningIndicator"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("2")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("SS Screening Indicator", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartSSScreeningIndicator(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartSSScreeningIndicator"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("2")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("SS Screening Indicator", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartSoLSACapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartSoLSACapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("SoLSA Capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartSoLSACapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartSoLSACapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("SoLSA Capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartRevisionLevelIndicator(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartRevisionLevelIndicator"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("Revision level indicator", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartRevisionLevelIndicator(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartRevisionLevelIndicator"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("Revision level indicator", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartPFCFeatureMode(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartPFCFeatureMode"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("PFC feature mode", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartPFCFeatureMode(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartPFCFeatureMode"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("PFC feature mode", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartExtendedGEABits(r *runtime.Reader) (ExtendedGEABits, error) {
	return decodeExtendedGEABits(r)
}
func encodeMSNetworkCapabilityValuePartExtendedGEABits(w *runtime.Writer, v ExtendedGEABits) error {
	return encodeExtendedGEABits(w, v)
}
func decodeMSNetworkCapabilityValuePartLCSVACapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartLCSVACapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("LCS VA capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartLCSVACapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartLCSVACapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("LCS VA capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartPSInterRATHOFromGERANToUTRANIuModeCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartPSInterRATHOFromGERANToUTRANIuModeCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("PS inter-RAT HO from GERAN to UTRAN Iu mode capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartPSInterRATHOFromGERANToUTRANIuModeCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartPSInterRATHOFromGERANToUTRANIuModeCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("PS inter-RAT HO from GERAN to UTRAN Iu mode capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartPSInterRATHOFromGERANToEUTRANS1ModeCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartPSInterRATHOFromGERANToEUTRANS1ModeCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("PS inter-RAT HO from GERAN to E-UTRAN S1 mode capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartPSInterRATHOFromGERANToEUTRANS1ModeCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartPSInterRATHOFromGERANToEUTRANS1ModeCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("PS inter-RAT HO from GERAN to E-UTRAN S1 mode capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartEMMCombinedProceduresCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartEMMCombinedProceduresCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("EMM Combined procedures Capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartEMMCombinedProceduresCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartEMMCombinedProceduresCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("EMM Combined procedures Capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartISRSupport(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartISRSupport"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("ISR support", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartISRSupport(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartISRSupport"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("ISR support", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartSRVCCToGERANUTRANCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartSRVCCToGERANUTRANCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("SRVCC to GERAN/UTRAN capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartSRVCCToGERANUTRANCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartSRVCCToGERANUTRANCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("SRVCC to GERAN/UTRAN capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartEPCCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartEPCCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("EPC capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartEPCCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartEPCCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("EPC capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartNFCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartNFCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("NF capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartNFCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartNFCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("NF capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartGERANNetworkSharingCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartGERANNetworkSharingCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GERAN network sharing capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartGERANNetworkSharingCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartGERANNetworkSharingCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GERAN network sharing capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartUserPlaneIntegrityProtectionSupport(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartUserPlaneIntegrityProtectionSupport"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("User plane integrity protection support", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartUserPlaneIntegrityProtectionSupport(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartUserPlaneIntegrityProtectionSupport"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("User plane integrity protection support", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartGIA4(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartGIA4"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GIA/4", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartGIA4(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartGIA4"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GIA/4", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartGIA5(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartGIA5"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GIA/5", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartGIA5(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartGIA5"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GIA/5", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartGIA6(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartGIA6"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GIA/6", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartGIA6(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartGIA6"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GIA/6", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartGIA7(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartGIA7"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GIA/7", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartGIA7(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartGIA7"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GIA/7", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartEPCOIEIndicator(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartEPCOIEIndicator"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("ePCO IE indicator", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartEPCOIEIndicator(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartEPCOIEIndicator"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("ePCO IE indicator", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartRestrictionOnUseOfEnhancedCoverageCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartRestrictionOnUseOfEnhancedCoverageCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("Restriction on use of enhanced coverage capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartRestrictionOnUseOfEnhancedCoverageCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartRestrictionOnUseOfEnhancedCoverageCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("Restriction on use of enhanced coverage capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartDualConnectivityOfEUTRAWithNRCapability(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("MSNetworkCapabilityValuePartDualConnectivityOfEUTRAWithNRCapability"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("Dual connectivity of E-UTRA with NR capability", v)
	return uint8(v), nil
}
func encodeMSNetworkCapabilityValuePartDualConnectivityOfEUTRAWithNRCapability(w *runtime.Writer, v uint8) error {
	if err := w.Enter("MSNetworkCapabilityValuePartDualConnectivityOfEUTRAWithNRCapability"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("Dual connectivity of E-UTRA with NR capability", uint64(v))
	return nil
}
func decodeMSNetworkCapabilityValuePartSpareBitsListEntry(r *runtime.Reader) (runtime.BitString, error) {
	return r.ReadSpare()
}
func encodeMSNetworkCapabilityValuePartSpareBitsListEntry(w *runtime.Writer, _ runtime.BitString) error {
	return w.WriteSpare()
}
func decodeMSNetworkCapabilityValuePartSpareBitsList(r *runtime.Reader) ([]runtime.BitString, error) {
	var out []runtime.BitString
	for r.Remaining() > 0 {
		v, err := decodeMSNetworkCapabilityValuePartSpareBitsListEntry(r)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	r.RecordSpareCount("MSNetworkCapabilityValuePartSpareBitsList", len(out))
	return out, nil
}
func encodeMSNetworkCapabilityValuePartSpareBitsList(w *runtime.Writer, _ []runtime.BitString) error {
	count, recorded := w.SpareCount("MSNetworkCapabilityValuePartSpareBitsList")
	if !recorded {
		count = w.SpareFillCount()
	}
	for i := 0; i < count; i++ {
		if err := encodeMSNetworkCapabilityValuePartSpareBitsListEntry(w, runtime.BitString{}); err != nil {
			return err
		}
	}
	return nil
}
func decodeMSNetworkCapabilityValuePart(r *runtime.Reader) (MSNetworkCapabilityValuePart, error) {
	if err := r.Enter("MSNetworkCapabilityValuePart"); err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	defer r.Leave()
	var v MSNetworkCapabilityValuePart
	x0, err := decodeMSNetworkCapabilityValuePartGEA1Bits(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.GEA1Bits = x0
	x1, err := decodeMSNetworkCapabilityValuePartSMCapabilitiesViaDedicatedChannels(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.SMCapabilitiesViaDedicatedChannels = x1
	x2, err := decodeMSNetworkCapabilityValuePartSMCapabilitiesViaGPRSChannels(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.SMCapabilitiesViaGPRSChannels = x2
	x3, err := decodeMSNetworkCapabilityValuePartUCS2Support(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.UCS2Support = x3
	x4, err := decodeMSNetworkCapabilityValuePartSSScreeningIndicator(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.SSScreeningIndicator = x4
	x5, err := decodeMSNetworkCapabilityValuePartSoLSACapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.SoLSACapability = x5
	x6, err := decodeMSNetworkCapabilityValuePartRevisionLevelIndicator(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.RevisionLevelIndicator = x6
	x7, err := decodeMSNetworkCapabilityValuePartPFCFeatureMode(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.PFCFeatureMode = x7
	x8, err := decodeMSNetworkCapabilityValuePartExtendedGEABits(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.ExtendedGEABits = x8
	x9, err := decodeMSNetworkCapabilityValuePartLCSVACapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.LCSVACapability = x9
	x10, err := decodeMSNetworkCapabilityValuePartPSInterRATHOFromGERANToUTRANIuModeCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.PSInterRATHOFromGERANToUTRANIuModeCapability = x10
	x11, err := decodeMSNetworkCapabilityValuePartPSInterRATHOFromGERANToEUTRANS1ModeCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.PSInterRATHOFromGERANToEUTRANS1ModeCapability = x11
	x12, err := decodeMSNetworkCapabilityValuePartEMMCombinedProceduresCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.EMMCombinedProceduresCapability = x12
	x13, err := decodeMSNetworkCapabilityValuePartISRSupport(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.ISRSupport = x13
	x14, err := decodeMSNetworkCapabilityValuePartSRVCCToGERANUTRANCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.SRVCCToGERANUTRANCapability = x14
	x15, err := decodeMSNetworkCapabilityValuePartEPCCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.EPCCapability = x15
	x16, err := decodeMSNetworkCapabilityValuePartNFCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.NFCapability = x16
	x17, err := decodeMSNetworkCapabilityValuePartGERANNetworkSharingCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.GERANNetworkSharingCapability = x17
	x18, err := decodeMSNetworkCapabilityValuePartUserPlaneIntegrityProtectionSupport(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.UserPlaneIntegrityProtectionSupport = x18
	x19, err := decodeMSNetworkCapabilityValuePartGIA4(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.GIA4 = x19
	x20, err := decodeMSNetworkCapabilityValuePartGIA5(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.GIA5 = x20
	x21, err := decodeMSNetworkCapabilityValuePartGIA6(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.GIA6 = x21
	x22, err := decodeMSNetworkCapabilityValuePartGIA7(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.GIA7 = x22
	x23, err := decodeMSNetworkCapabilityValuePartEPCOIEIndicator(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.EPCOIEIndicator = x23
	x24, err := decodeMSNetworkCapabilityValuePartRestrictionOnUseOfEnhancedCoverageCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.RestrictionOnUseOfEnhancedCoverageCapability = x24
	x25, err := decodeMSNetworkCapabilityValuePartDualConnectivityOfEUTRAWithNRCapability(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	v.DualConnectivityOfEUTRAWithNRCapability = x25
	x26, err := decodeMSNetworkCapabilityValuePartSpareBitsList(r)
	if err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	_ = x26
	return v, nil
}
func encodeMSNetworkCapabilityValuePart(w *runtime.Writer, v MSNetworkCapabilityValuePart) error {
	if err := w.Enter("MSNetworkCapabilityValuePart"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 27
	if n, ok := w.Truncation("MSNetworkCapabilityValuePart"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.GEA1Bits) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GEA1Bits")
	}
	if limit > 0 {
		if err := encodeMSNetworkCapabilityValuePartGEA1Bits(w, v.GEA1Bits); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.SMCapabilitiesViaDedicatedChannels) {
		return fmt.Errorf("edit to field beyond transmitted truncation: SMCapabilitiesViaDedicatedChannels")
	}
	if limit > 1 {
		if err := encodeMSNetworkCapabilityValuePartSMCapabilitiesViaDedicatedChannels(w, v.SMCapabilitiesViaDedicatedChannels); err != nil {
			return err
		}
	}
	if limit <= 2 && !runtime.IsZero(v.SMCapabilitiesViaGPRSChannels) {
		return fmt.Errorf("edit to field beyond transmitted truncation: SMCapabilitiesViaGPRSChannels")
	}
	if limit > 2 {
		if err := encodeMSNetworkCapabilityValuePartSMCapabilitiesViaGPRSChannels(w, v.SMCapabilitiesViaGPRSChannels); err != nil {
			return err
		}
	}
	if limit <= 3 && !runtime.IsZero(v.UCS2Support) {
		return fmt.Errorf("edit to field beyond transmitted truncation: UCS2Support")
	}
	if limit > 3 {
		if err := encodeMSNetworkCapabilityValuePartUCS2Support(w, v.UCS2Support); err != nil {
			return err
		}
	}
	if limit <= 4 && !runtime.IsZero(v.SSScreeningIndicator) {
		return fmt.Errorf("edit to field beyond transmitted truncation: SSScreeningIndicator")
	}
	if limit > 4 {
		if err := encodeMSNetworkCapabilityValuePartSSScreeningIndicator(w, v.SSScreeningIndicator); err != nil {
			return err
		}
	}
	if limit <= 5 && !runtime.IsZero(v.SoLSACapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: SoLSACapability")
	}
	if limit > 5 {
		if err := encodeMSNetworkCapabilityValuePartSoLSACapability(w, v.SoLSACapability); err != nil {
			return err
		}
	}
	if limit <= 6 && !runtime.IsZero(v.RevisionLevelIndicator) {
		return fmt.Errorf("edit to field beyond transmitted truncation: RevisionLevelIndicator")
	}
	if limit > 6 {
		if err := encodeMSNetworkCapabilityValuePartRevisionLevelIndicator(w, v.RevisionLevelIndicator); err != nil {
			return err
		}
	}
	if limit <= 7 && !runtime.IsZero(v.PFCFeatureMode) {
		return fmt.Errorf("edit to field beyond transmitted truncation: PFCFeatureMode")
	}
	if limit > 7 {
		if err := encodeMSNetworkCapabilityValuePartPFCFeatureMode(w, v.PFCFeatureMode); err != nil {
			return err
		}
	}
	if limit <= 8 && !runtime.IsZero(v.ExtendedGEABits) {
		return fmt.Errorf("edit to field beyond transmitted truncation: ExtendedGEABits")
	}
	if limit > 8 {
		if err := encodeMSNetworkCapabilityValuePartExtendedGEABits(w, v.ExtendedGEABits); err != nil {
			return err
		}
	}
	if limit <= 9 && !runtime.IsZero(v.LCSVACapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: LCSVACapability")
	}
	if limit > 9 {
		if err := encodeMSNetworkCapabilityValuePartLCSVACapability(w, v.LCSVACapability); err != nil {
			return err
		}
	}
	if limit <= 10 && !runtime.IsZero(v.PSInterRATHOFromGERANToUTRANIuModeCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: PSInterRATHOFromGERANToUTRANIuModeCapability")
	}
	if limit > 10 {
		if err := encodeMSNetworkCapabilityValuePartPSInterRATHOFromGERANToUTRANIuModeCapability(w, v.PSInterRATHOFromGERANToUTRANIuModeCapability); err != nil {
			return err
		}
	}
	if limit <= 11 && !runtime.IsZero(v.PSInterRATHOFromGERANToEUTRANS1ModeCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: PSInterRATHOFromGERANToEUTRANS1ModeCapability")
	}
	if limit > 11 {
		if err := encodeMSNetworkCapabilityValuePartPSInterRATHOFromGERANToEUTRANS1ModeCapability(w, v.PSInterRATHOFromGERANToEUTRANS1ModeCapability); err != nil {
			return err
		}
	}
	if limit <= 12 && !runtime.IsZero(v.EMMCombinedProceduresCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: EMMCombinedProceduresCapability")
	}
	if limit > 12 {
		if err := encodeMSNetworkCapabilityValuePartEMMCombinedProceduresCapability(w, v.EMMCombinedProceduresCapability); err != nil {
			return err
		}
	}
	if limit <= 13 && !runtime.IsZero(v.ISRSupport) {
		return fmt.Errorf("edit to field beyond transmitted truncation: ISRSupport")
	}
	if limit > 13 {
		if err := encodeMSNetworkCapabilityValuePartISRSupport(w, v.ISRSupport); err != nil {
			return err
		}
	}
	if limit <= 14 && !runtime.IsZero(v.SRVCCToGERANUTRANCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: SRVCCToGERANUTRANCapability")
	}
	if limit > 14 {
		if err := encodeMSNetworkCapabilityValuePartSRVCCToGERANUTRANCapability(w, v.SRVCCToGERANUTRANCapability); err != nil {
			return err
		}
	}
	if limit <= 15 && !runtime.IsZero(v.EPCCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: EPCCapability")
	}
	if limit > 15 {
		if err := encodeMSNetworkCapabilityValuePartEPCCapability(w, v.EPCCapability); err != nil {
			return err
		}
	}
	if limit <= 16 && !runtime.IsZero(v.NFCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: NFCapability")
	}
	if limit > 16 {
		if err := encodeMSNetworkCapabilityValuePartNFCapability(w, v.NFCapability); err != nil {
			return err
		}
	}
	if limit <= 17 && !runtime.IsZero(v.GERANNetworkSharingCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GERANNetworkSharingCapability")
	}
	if limit > 17 {
		if err := encodeMSNetworkCapabilityValuePartGERANNetworkSharingCapability(w, v.GERANNetworkSharingCapability); err != nil {
			return err
		}
	}
	if limit <= 18 && !runtime.IsZero(v.UserPlaneIntegrityProtectionSupport) {
		return fmt.Errorf("edit to field beyond transmitted truncation: UserPlaneIntegrityProtectionSupport")
	}
	if limit > 18 {
		if err := encodeMSNetworkCapabilityValuePartUserPlaneIntegrityProtectionSupport(w, v.UserPlaneIntegrityProtectionSupport); err != nil {
			return err
		}
	}
	if limit <= 19 && !runtime.IsZero(v.GIA4) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GIA4")
	}
	if limit > 19 {
		if err := encodeMSNetworkCapabilityValuePartGIA4(w, v.GIA4); err != nil {
			return err
		}
	}
	if limit <= 20 && !runtime.IsZero(v.GIA5) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GIA5")
	}
	if limit > 20 {
		if err := encodeMSNetworkCapabilityValuePartGIA5(w, v.GIA5); err != nil {
			return err
		}
	}
	if limit <= 21 && !runtime.IsZero(v.GIA6) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GIA6")
	}
	if limit > 21 {
		if err := encodeMSNetworkCapabilityValuePartGIA6(w, v.GIA6); err != nil {
			return err
		}
	}
	if limit <= 22 && !runtime.IsZero(v.GIA7) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GIA7")
	}
	if limit > 22 {
		if err := encodeMSNetworkCapabilityValuePartGIA7(w, v.GIA7); err != nil {
			return err
		}
	}
	if limit <= 23 && !runtime.IsZero(v.EPCOIEIndicator) {
		return fmt.Errorf("edit to field beyond transmitted truncation: EPCOIEIndicator")
	}
	if limit > 23 {
		if err := encodeMSNetworkCapabilityValuePartEPCOIEIndicator(w, v.EPCOIEIndicator); err != nil {
			return err
		}
	}
	if limit <= 24 && !runtime.IsZero(v.RestrictionOnUseOfEnhancedCoverageCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: RestrictionOnUseOfEnhancedCoverageCapability")
	}
	if limit > 24 {
		if err := encodeMSNetworkCapabilityValuePartRestrictionOnUseOfEnhancedCoverageCapability(w, v.RestrictionOnUseOfEnhancedCoverageCapability); err != nil {
			return err
		}
	}
	if limit <= 25 && !runtime.IsZero(v.DualConnectivityOfEUTRAWithNRCapability) {
		return fmt.Errorf("edit to field beyond transmitted truncation: DualConnectivityOfEUTRAWithNRCapability")
	}
	if limit > 25 {
		if err := encodeMSNetworkCapabilityValuePartDualConnectivityOfEUTRAWithNRCapability(w, v.DualConnectivityOfEUTRAWithNRCapability); err != nil {
			return err
		}
	}
	if limit > 26 {
		if err := encodeMSNetworkCapabilityValuePartSpareBitsList(w, nil); err != nil {
			return err
		}
	}
	return nil
}
func decodeGEA1BitsGEA1(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("GEA1BitsGEA1"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GEA/1", v)
	return uint8(v), nil
}
func encodeGEA1BitsGEA1(w *runtime.Writer, v uint8) error {
	if err := w.Enter("GEA1BitsGEA1"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GEA/1", uint64(v))
	return nil
}
func decodeGEA1Bits(r *runtime.Reader) (GEA1Bits, error) {
	if err := r.Enter("GEA1Bits"); err != nil {
		return GEA1Bits{}, err
	}
	defer r.Leave()
	var v GEA1Bits
	x0, err := decodeGEA1BitsGEA1(r)
	if err != nil {
		return GEA1Bits{}, err
	}
	v.GEA1 = x0
	return v, nil
}
func encodeGEA1Bits(w *runtime.Writer, v GEA1Bits) error {
	if err := w.Enter("GEA1Bits"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 1
	if n, ok := w.Truncation("GEA1Bits"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.GEA1) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GEA1")
	}
	if limit > 0 {
		if err := encodeGEA1BitsGEA1(w, v.GEA1); err != nil {
			return err
		}
	}
	return nil
}
func decodeExtendedGEABitsGEA2(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("ExtendedGEABitsGEA2"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GEA/2", v)
	return uint8(v), nil
}
func encodeExtendedGEABitsGEA2(w *runtime.Writer, v uint8) error {
	if err := w.Enter("ExtendedGEABitsGEA2"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GEA/2", uint64(v))
	return nil
}
func decodeExtendedGEABitsGEA3(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("ExtendedGEABitsGEA3"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GEA/3", v)
	return uint8(v), nil
}
func encodeExtendedGEABitsGEA3(w *runtime.Writer, v uint8) error {
	if err := w.Enter("ExtendedGEABitsGEA3"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GEA/3", uint64(v))
	return nil
}
func decodeExtendedGEABitsGEA4(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("ExtendedGEABitsGEA4"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GEA/4", v)
	return uint8(v), nil
}
func encodeExtendedGEABitsGEA4(w *runtime.Writer, v uint8) error {
	if err := w.Enter("ExtendedGEABitsGEA4"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GEA/4", uint64(v))
	return nil
}
func decodeExtendedGEABitsGEA5(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("ExtendedGEABitsGEA5"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GEA/5", v)
	return uint8(v), nil
}
func encodeExtendedGEABitsGEA5(w *runtime.Writer, v uint8) error {
	if err := w.Enter("ExtendedGEABitsGEA5"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GEA/5", uint64(v))
	return nil
}
func decodeExtendedGEABitsGEA6(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("ExtendedGEABitsGEA6"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GEA/6", v)
	return uint8(v), nil
}
func encodeExtendedGEABitsGEA6(w *runtime.Writer, v uint8) error {
	if err := w.Enter("ExtendedGEABitsGEA6"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GEA/6", uint64(v))
	return nil
}
func decodeExtendedGEABitsGEA7(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("ExtendedGEABitsGEA7"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("1")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("GEA/7", v)
	return uint8(v), nil
}
func encodeExtendedGEABitsGEA7(w *runtime.Writer, v uint8) error {
	if err := w.Enter("ExtendedGEABitsGEA7"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("1")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("GEA/7", uint64(v))
	return nil
}
func decodeExtendedGEABits(r *runtime.Reader) (ExtendedGEABits, error) {
	if err := r.Enter("ExtendedGEABits"); err != nil {
		return ExtendedGEABits{}, err
	}
	defer r.Leave()
	var v ExtendedGEABits
	x0, err := decodeExtendedGEABitsGEA2(r)
	if err != nil {
		return ExtendedGEABits{}, err
	}
	v.GEA2 = x0
	x1, err := decodeExtendedGEABitsGEA3(r)
	if err != nil {
		return ExtendedGEABits{}, err
	}
	v.GEA3 = x1
	x2, err := decodeExtendedGEABitsGEA4(r)
	if err != nil {
		return ExtendedGEABits{}, err
	}
	v.GEA4 = x2
	x3, err := decodeExtendedGEABitsGEA5(r)
	if err != nil {
		return ExtendedGEABits{}, err
	}
	v.GEA5 = x3
	x4, err := decodeExtendedGEABitsGEA6(r)
	if err != nil {
		return ExtendedGEABits{}, err
	}
	v.GEA6 = x4
	x5, err := decodeExtendedGEABitsGEA7(r)
	if err != nil {
		return ExtendedGEABits{}, err
	}
	v.GEA7 = x5
	return v, nil
}
func encodeExtendedGEABits(w *runtime.Writer, v ExtendedGEABits) error {
	if err := w.Enter("ExtendedGEABits"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 6
	if n, ok := w.Truncation("ExtendedGEABits"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.GEA2) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GEA2")
	}
	if limit > 0 {
		if err := encodeExtendedGEABitsGEA2(w, v.GEA2); err != nil {
			return err
		}
	}
	if limit <= 1 && !runtime.IsZero(v.GEA3) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GEA3")
	}
	if limit > 1 {
		if err := encodeExtendedGEABitsGEA3(w, v.GEA3); err != nil {
			return err
		}
	}
	if limit <= 2 && !runtime.IsZero(v.GEA4) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GEA4")
	}
	if limit > 2 {
		if err := encodeExtendedGEABitsGEA4(w, v.GEA4); err != nil {
			return err
		}
	}
	if limit <= 3 && !runtime.IsZero(v.GEA5) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GEA5")
	}
	if limit > 3 {
		if err := encodeExtendedGEABitsGEA5(w, v.GEA5); err != nil {
			return err
		}
	}
	if limit <= 4 && !runtime.IsZero(v.GEA6) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GEA6")
	}
	if limit > 4 {
		if err := encodeExtendedGEABitsGEA6(w, v.GEA6); err != nil {
			return err
		}
	}
	if limit <= 5 && !runtime.IsZero(v.GEA7) {
		return fmt.Errorf("edit to field beyond transmitted truncation: GEA7")
	}
	if limit > 5 {
		if err := encodeExtendedGEABitsGEA7(w, v.GEA7); err != nil {
			return err
		}
	}
	return nil
}
func decodeSpareBitsAlternativesAltUnlabeled(_ *runtime.Reader) (struct{}, error) {
	return struct{}{}, nil
}
func encodeSpareBitsAlternativesAltUnlabeled(_ *runtime.Writer, _ struct{}) error { return nil }
func decodeSpareBitsAlternativesAltUnlabeledVariant2SpareBit(r *runtime.Reader) (runtime.BitString, error) {
	return r.ReadSpare()
}
func encodeSpareBitsAlternativesAltUnlabeledVariant2SpareBit(w *runtime.Writer, _ runtime.BitString) error {
	return w.WriteSpare()
}
func decodeSpareBitsAlternativesAltUnlabeledVariant2SpareBitsListEntry(r *runtime.Reader) (runtime.BitString, error) {
	return r.ReadSpare()
}
func encodeSpareBitsAlternativesAltUnlabeledVariant2SpareBitsListEntry(w *runtime.Writer, _ runtime.BitString) error {
	return w.WriteSpare()
}
func decodeSpareBitsAlternativesAltUnlabeledVariant2SpareBitsList(r *runtime.Reader) ([]runtime.BitString, error) {
	var out []runtime.BitString
	for r.Remaining() > 0 {
		v, err := decodeSpareBitsAlternativesAltUnlabeledVariant2SpareBitsListEntry(r)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	r.RecordSpareCount("SpareBitsAlternativesAltUnlabeledVariant2SpareBitsList", len(out))
	return out, nil
}
func encodeSpareBitsAlternativesAltUnlabeledVariant2SpareBitsList(w *runtime.Writer, _ []runtime.BitString) error {
	count, recorded := w.SpareCount("SpareBitsAlternativesAltUnlabeledVariant2SpareBitsList")
	if !recorded {
		count = w.SpareFillCount()
	}
	for i := 0; i < count; i++ {
		if err := encodeSpareBitsAlternativesAltUnlabeledVariant2SpareBitsListEntry(w, runtime.BitString{}); err != nil {
			return err
		}
	}
	return nil
}
func decodeSpareBitsAlternativesAltUnlabeledVariant2(r *runtime.Reader) (SpareBitsAlternativesAltUnlabeledVariant2, error) {
	if err := r.Enter("SpareBitsAlternativesAltUnlabeledVariant2"); err != nil {
		return SpareBitsAlternativesAltUnlabeledVariant2{}, err
	}
	defer r.Leave()
	var v SpareBitsAlternativesAltUnlabeledVariant2
	x0, err := decodeSpareBitsAlternativesAltUnlabeledVariant2SpareBit(r)
	if err != nil {
		return SpareBitsAlternativesAltUnlabeledVariant2{}, err
	}
	_ = x0
	x1, err := decodeSpareBitsAlternativesAltUnlabeledVariant2SpareBitsList(r)
	if err != nil {
		return SpareBitsAlternativesAltUnlabeledVariant2{}, err
	}
	_ = x1
	return v, nil
}
func encodeSpareBitsAlternativesAltUnlabeledVariant2(w *runtime.Writer, v SpareBitsAlternativesAltUnlabeledVariant2) error {
	if err := w.Enter("SpareBitsAlternativesAltUnlabeledVariant2"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("SpareBitsAlternativesAltUnlabeledVariant2"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeSpareBitsAlternativesAltUnlabeledVariant2SpareBit(w, runtime.BitString{}); err != nil {
			return err
		}
	}
	if limit > 1 {
		if err := encodeSpareBitsAlternativesAltUnlabeledVariant2SpareBitsList(w, nil); err != nil {
			return err
		}
	}
	return nil
}
func decodeSpareBitsAlternatives(r *runtime.Reader) (SpareBitsAlternatives, error) {
	var result SpareBitsAlternatives
	matches := 0
	var chosen *runtime.Reader
	var truncatedErr error
	if r.Remaining() == 0 {
		{
			candidate := r.Fork()
			v, err := decodeSpareBitsAlternativesAltUnlabeled(candidate)
			if err == nil {
				matches++
				chosen = candidate
				_ = v
				result.Alternative = SpareBitsAlternativesAlternativeAltUnlabeled
				result.AltUnlabeled = &v
			} else {
				truncatedErr = runtime.PreferTruncation(truncatedErr, err)
			}
		}
	}
	{
		candidate := r.Fork()
		v, err := decodeSpareBitsAlternativesAltUnlabeledVariant2(candidate)
		if err == nil {
			matches++
			chosen = candidate
			_ = v
			result.Alternative = SpareBitsAlternativesAlternativeAltUnlabeledVariant2
			result.AltUnlabeledVariant2 = &v
		} else {
			truncatedErr = runtime.PreferTruncation(truncatedErr, err)
		}
	}
	if matches == 0 && truncatedErr != nil {
		return result, truncatedErr
	}
	if matches != 1 {
		return result, r.Error(runtime.InvalidBranch, fmt.Sprintf("choice has %d matching alternatives", matches))
	}
	r.Commit(chosen)
	return result, nil
}
func encodeSpareBitsAlternatives(w *runtime.Writer, v SpareBitsAlternatives) error {
	count := 0
	if v.AltUnlabeled != nil {
		count++
	}
	if v.AltUnlabeledVariant2 != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("choice requires exactly one alternative")
	}
	switch v.Alternative {
	case SpareBitsAlternativesAlternativeAltUnlabeled:
		if v.AltUnlabeled == nil {
			return fmt.Errorf("choice alternative mismatch")
		}
		return encodeSpareBitsAlternativesAltUnlabeled(w, *v.AltUnlabeled)
	case SpareBitsAlternativesAlternativeAltUnlabeledVariant2:
		if v.AltUnlabeledVariant2 == nil {
			return fmt.Errorf("choice alternative mismatch")
		}
		return encodeSpareBitsAlternativesAltUnlabeledVariant2(w, *v.AltUnlabeledVariant2)
	default:
		return fmt.Errorf("invalid choice alternative")
	}
}
func decodeSpareBits(r *runtime.Reader) (SpareBits, error) {
	if err := r.Enter("SpareBits"); err != nil {
		return SpareBits{}, err
	}
	defer r.Leave()
	var v SpareBits
	x0, err := decodeSpareBitsAlternatives(r)
	if err != nil {
		return SpareBits{}, err
	}
	v.Alternatives = x0
	return v, nil
}
func encodeSpareBits(w *runtime.Writer, v SpareBits) error {
	if err := w.Enter("SpareBits"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 1
	if n, ok := w.Truncation("SpareBits"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit <= 0 && !runtime.IsZero(v.Alternatives) {
		return fmt.Errorf("edit to field beyond transmitted truncation: Alternatives")
	}
	if limit > 0 {
		if err := encodeSpareBitsAlternatives(w, v.Alternatives); err != nil {
			return err
		}
	}
	return nil
}

// Maximum encoded extent: TS 24.008 V20.1.0 §10.5.5.12 (10-octet type 4 IE minus IEI and length = 8-octet value part).
// DecodeMSNetworkCapabilityValuePart decodes TS 24.008 V20.1.0 §10.5.5.12 <MS network capability value part>.
func DecodeMSNetworkCapabilityValuePartFrom(r *runtime.Reader) (MSNetworkCapabilityValuePart, error) {
	if err := r.Check(); err != nil {
		return MSNetworkCapabilityValuePart{}, err
	}
	return decodeMSNetworkCapabilityValuePart(r)
}
func EncodeMSNetworkCapabilityValuePartTo(w *runtime.Writer, v MSNetworkCapabilityValuePart) error {
	return encodeMSNetworkCapabilityValuePart(w, v)
}
func DecodeMSNetworkCapabilityValuePart(data []byte) (runtime.Decoded[MSNetworkCapabilityValuePart], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[MSNetworkCapabilityValuePart]{}, err
	}
	if len(data) < 1 {
		return runtime.Decoded[MSNetworkCapabilityValuePart]{}, &runtime.DecodeError{Kind: runtime.Truncated, Offset: runtime.InputBits(data), Detail: "MSNetworkCapabilityValuePart requires at least 8 bits"}
	}
	input := data
	if len(data) > 8 {
		input = data[:8]
	}
	r := runtime.NewReader(input)
	r.SetZeroExtension(true)
	v, err := decodeMSNetworkCapabilityValuePart(r)
	if err != nil {
		return runtime.Decoded[MSNetworkCapabilityValuePart]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[MSNetworkCapabilityValuePart]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeMSNetworkCapabilityValuePart encodes an edited or newly constructed value through direct bit operations.
func EncodeMSNetworkCapabilityValuePart(v MSNetworkCapabilityValuePart) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(true)
	if err := encodeMSNetworkCapabilityValuePart(w, v); err != nil {
		return nil, err
	}
	if err := w.PadMinimum(8, false); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	if len(out) < 1 {
		return nil, fmt.Errorf("MSNetworkCapabilityValuePart requires at least 8 bits")
	}
	return out, nil
}

// Canonical maximum: TS 24.008 V20.1.0 §10.5.5.12 (10-octet type 4 IE minus IEI and length = 8-octet value part).
// EncodeMSNetworkCapabilityValuePartCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeMSNetworkCapabilityValuePartCanonical(v MSNetworkCapabilityValuePart) ([]byte, error) {
	return runtime.CanonicalEncode(v, 1, 8, true, EncodeMSNetworkCapabilityValuePart, DecodeMSNetworkCapabilityValuePart, nil)
}

// EncodeMSNetworkCapabilityValuePartCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeMSNetworkCapabilityValuePartCanonicalAtLength(v MSNetworkCapabilityValuePart, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 1, 8, EncodeMSNetworkCapabilityValuePart, DecodeMSNetworkCapabilityValuePart, nil)
}

// DecodeGEA1Bits decodes TS 24.008 V20.1.0 §10.5.5.12 <GEA1 bits>.
func DecodeGEA1BitsFrom(r *runtime.Reader) (GEA1Bits, error) {
	if err := r.Check(); err != nil {
		return GEA1Bits{}, err
	}
	return decodeGEA1Bits(r)
}
func EncodeGEA1BitsTo(w *runtime.Writer, v GEA1Bits) error { return encodeGEA1Bits(w, v) }
func DecodeGEA1Bits(data []byte) (runtime.Decoded[GEA1Bits], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[GEA1Bits]{}, err
	}
	input := data
	r := runtime.NewReader(input)
	r.SetZeroExtension(false)
	v, err := decodeGEA1Bits(r)
	if err != nil {
		return runtime.Decoded[GEA1Bits]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[GEA1Bits]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeGEA1Bits encodes an edited or newly constructed value through direct bit operations.
func EncodeGEA1Bits(v GEA1Bits) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(false)
	if err := encodeGEA1Bits(w, v); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Canonical maximum: TS 24.008 V20.1.0 §10.5.5.12 (finite maximum from the printed CSN.1 grammar).
// EncodeGEA1BitsCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeGEA1BitsCanonical(v GEA1Bits) ([]byte, error) {
	return runtime.CanonicalEncode(v, 0, 1, false, EncodeGEA1Bits, DecodeGEA1Bits, nil)
}

// EncodeGEA1BitsCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeGEA1BitsCanonicalAtLength(v GEA1Bits, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 0, 1, EncodeGEA1Bits, DecodeGEA1Bits, nil)
}

// DecodeExtendedGEABits decodes TS 24.008 V20.1.0 §10.5.5.12 <Extended GEA bits>.
func DecodeExtendedGEABitsFrom(r *runtime.Reader) (ExtendedGEABits, error) {
	if err := r.Check(); err != nil {
		return ExtendedGEABits{}, err
	}
	return decodeExtendedGEABits(r)
}
func EncodeExtendedGEABitsTo(w *runtime.Writer, v ExtendedGEABits) error {
	return encodeExtendedGEABits(w, v)
}
func DecodeExtendedGEABits(data []byte) (runtime.Decoded[ExtendedGEABits], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[ExtendedGEABits]{}, err
	}
	input := data
	r := runtime.NewReader(input)
	r.SetZeroExtension(false)
	v, err := decodeExtendedGEABits(r)
	if err != nil {
		return runtime.Decoded[ExtendedGEABits]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[ExtendedGEABits]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeExtendedGEABits encodes an edited or newly constructed value through direct bit operations.
func EncodeExtendedGEABits(v ExtendedGEABits) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(false)
	if err := encodeExtendedGEABits(w, v); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Canonical maximum: TS 24.008 V20.1.0 §10.5.5.12 (finite maximum from the printed CSN.1 grammar).
// EncodeExtendedGEABitsCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeExtendedGEABitsCanonical(v ExtendedGEABits) ([]byte, error) {
	return runtime.CanonicalEncode(v, 0, 1, false, EncodeExtendedGEABits, DecodeExtendedGEABits, nil)
}

// EncodeExtendedGEABitsCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeExtendedGEABitsCanonicalAtLength(v ExtendedGEABits, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 0, 1, EncodeExtendedGEABits, DecodeExtendedGEABits, nil)
}

// DecodeSpareBits decodes TS 24.008 V20.1.0 §10.5.5.12 <Spare bits>.
func DecodeSpareBitsFrom(r *runtime.Reader) (SpareBits, error) {
	if err := r.Check(); err != nil {
		return SpareBits{}, err
	}
	return decodeSpareBits(r)
}
func EncodeSpareBitsTo(w *runtime.Writer, v SpareBits) error { return encodeSpareBits(w, v) }
func DecodeSpareBits(data []byte) (runtime.Decoded[SpareBits], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[SpareBits]{}, err
	}
	input := data
	r := runtime.NewReader(input)
	r.SetZeroExtension(false)
	v, err := decodeSpareBits(r)
	if err != nil {
		return runtime.Decoded[SpareBits]{}, err
	}
	tail := runtime.TrailingBits(data, r.Position())
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[SpareBits]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeSpareBits encodes an edited or newly constructed value through direct bit operations.
func EncodeSpareBits(v SpareBits) ([]byte, error) {
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	w.SetZeroExtension(false)
	if err := encodeSpareBits(w, v); err != nil {
		return nil, err
	}
	out, err := w.Finish(v.Wire.Tail)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Canonical maximum: TS 24.008 V20.1.0 §10.5.5.12 (MS network capability value part maximum 8 octets).
// EncodeSpareBitsCanonical encodes a fresh semantic value using source-defined minimum length, truncation and padding. It requires CanonicalAtLength when no standalone maximum is defined.
func EncodeSpareBitsCanonical(v SpareBits) ([]byte, error) {
	return runtime.CanonicalEncode(v, 0, 8, false, EncodeSpareBits, DecodeSpareBits, nil)
}

// EncodeSpareBitsCanonicalAtLength encodes into the value length supplied by the containing message.
func EncodeSpareBitsCanonicalAtLength(v SpareBits, octets int) ([]byte, error) {
	return runtime.CanonicalEncodeAtLength(v, octets, 0, 8, EncodeSpareBits, DecodeSpareBits, nil)
}
func Definitions() []string {
	return []string{"MS network capability value part", "GEA1 bits", "Extended GEA bits", "Spare bits"}
}
func Descriptors() []runtime.Descriptor {
	return []runtime.Descriptor{
		{Standard: "TS 24.008", Version: "20.1.0", Clause: "10.5.5.12", Name: "MS network capability value part", MaxOctets: 8, Decode: func(data []byte) (any, error) { return DecodeMSNetworkCapabilityValuePart(data) }, DecodeFrom: func(r *runtime.Reader) (any, error) { return DecodeMSNetworkCapabilityValuePartFrom(r) }, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case MSNetworkCapabilityValuePart:
				return EncodeMSNetworkCapabilityValuePart(v)
			case runtime.Decoded[MSNetworkCapabilityValuePart]:
				return EncodeMSNetworkCapabilityValuePart(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for MSNetworkCapabilityValuePart")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case MSNetworkCapabilityValuePart:
				return EncodeMSNetworkCapabilityValuePartCanonical(v)
			case runtime.Decoded[MSNetworkCapabilityValuePart]:
				return EncodeMSNetworkCapabilityValuePartCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for MSNetworkCapabilityValuePart")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case MSNetworkCapabilityValuePart:
				return EncodeMSNetworkCapabilityValuePartCanonicalAtLength(v, octets)
			case runtime.Decoded[MSNetworkCapabilityValuePart]:
				return EncodeMSNetworkCapabilityValuePartCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for MSNetworkCapabilityValuePart")
			}
		}},
		{Standard: "TS 24.008", Version: "20.1.0", Clause: "10.5.5.12", Name: "GEA1 bits", MaxOctets: 1, Decode: func(data []byte) (any, error) { return DecodeGEA1Bits(data) }, DecodeFrom: func(r *runtime.Reader) (any, error) { return DecodeGEA1BitsFrom(r) }, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case GEA1Bits:
				return EncodeGEA1Bits(v)
			case runtime.Decoded[GEA1Bits]:
				return EncodeGEA1Bits(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for GEA1Bits")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case GEA1Bits:
				return EncodeGEA1BitsCanonical(v)
			case runtime.Decoded[GEA1Bits]:
				return EncodeGEA1BitsCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for GEA1Bits")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case GEA1Bits:
				return EncodeGEA1BitsCanonicalAtLength(v, octets)
			case runtime.Decoded[GEA1Bits]:
				return EncodeGEA1BitsCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for GEA1Bits")
			}
		}},
		{Standard: "TS 24.008", Version: "20.1.0", Clause: "10.5.5.12", Name: "Extended GEA bits", MaxOctets: 1, Decode: func(data []byte) (any, error) { return DecodeExtendedGEABits(data) }, DecodeFrom: func(r *runtime.Reader) (any, error) { return DecodeExtendedGEABitsFrom(r) }, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case ExtendedGEABits:
				return EncodeExtendedGEABits(v)
			case runtime.Decoded[ExtendedGEABits]:
				return EncodeExtendedGEABits(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for ExtendedGEABits")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case ExtendedGEABits:
				return EncodeExtendedGEABitsCanonical(v)
			case runtime.Decoded[ExtendedGEABits]:
				return EncodeExtendedGEABitsCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for ExtendedGEABits")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case ExtendedGEABits:
				return EncodeExtendedGEABitsCanonicalAtLength(v, octets)
			case runtime.Decoded[ExtendedGEABits]:
				return EncodeExtendedGEABitsCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for ExtendedGEABits")
			}
		}},
		{Standard: "TS 24.008", Version: "20.1.0", Clause: "10.5.5.12", Name: "Spare bits", MaxOctets: 8, Decode: func(data []byte) (any, error) { return DecodeSpareBits(data) }, DecodeFrom: func(r *runtime.Reader) (any, error) { return DecodeSpareBitsFrom(r) }, Encode: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case SpareBits:
				return EncodeSpareBits(v)
			case runtime.Decoded[SpareBits]:
				return EncodeSpareBits(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for SpareBits")
			}
		}, Canonical: func(value any) ([]byte, error) {
			switch v := value.(type) {
			case SpareBits:
				return EncodeSpareBitsCanonical(v)
			case runtime.Decoded[SpareBits]:
				return EncodeSpareBitsCanonical(v.Value)
			default:
				return nil, fmt.Errorf("wrong value type for SpareBits")
			}
		}, CanonicalAtLength: func(value any, octets int) ([]byte, error) {
			switch v := value.(type) {
			case SpareBits:
				return EncodeSpareBitsCanonicalAtLength(v, octets)
			case runtime.Decoded[SpareBits]:
				return EncodeSpareBitsCanonicalAtLength(v.Value, octets)
			default:
				return nil, fmt.Errorf("wrong value type for SpareBits")
			}
		}},
	}
}
func Lookup(name string) (runtime.Descriptor, error) {
	var matches []runtime.Descriptor
	for _, d := range Descriptors() {
		if d.Name == name {
			matches = append(matches, d)
		}
	}
	if len(matches) == 1 {
		return matches[0], nil
	}
	if len(matches) == 0 {
		return runtime.Descriptor{}, fmt.Errorf("unknown CSN.1 definition %q", name)
	}
	var clauses []string
	for _, d := range matches {
		clauses = append(clauses, d.Clause)
	}
	return runtime.Descriptor{}, fmt.Errorf("ambiguous CSN.1 definition %q in clauses %v", name, clauses)
}
func LookupClause(clause, name string) (runtime.Descriptor, error) {
	for _, d := range Descriptors() {
		if d.Clause == clause && d.Name == name {
			return d, nil
		}
	}
	return runtime.Descriptor{}, fmt.Errorf("unknown CSN.1 definition %q in clause %s", name, clause)
}
