// Code generated by csn1c from TS 44.060 V19.0.0 §12; DO NOT EDIT.
// Extracted source SHA-256: 30ea870638c095c9875aaffcdf2005994517a68ace6f69c943b072eee9946388.
package ies

import (
	"fmt"
	"github.com/gomaja/go-csn1/runtime"
)

type EGPRSWindowSizeIE struct {
	EGPRSWindowSize uint8
	Wire            runtime.WireInfo `json:"-"`
}
type EGPRSModulationAndCodingIE struct {
	EGPRSModulationAndCodingScheme uint8
	Wire                           runtime.WireInfo `json:"-"`
}
type EGPRSLevelIE struct {
	EGPRSLevel uint8
	Wire       runtime.WireInfo `json:"-"`
}
type PacketTimingAdvanceIETIMINGADVANCEINDEXGroup struct {
	TIMINGADVANCEINDEX          uint8
	TIMINGADVANCETIMESLOTNUMBER uint8
}
type PacketTimingAdvanceIE struct {
	TIMINGADVANCEVALUE      *uint8
	TIMINGADVANCEINDEXGroup *PacketTimingAdvanceIETIMINGADVANCEINDEXGroup
	Wire                    runtime.WireInfo `json:"-"`
}
type TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID struct {
	MBMSSERVICEID uint32
}
type TMGIIEMBMSSERVICEIDChoiceMCC struct {
	MBMSSERVICEID uint32
	MCC           uint16
	MNC           uint16
}
type TMGIIEMBMSSERVICEIDChoiceAlternative uint8

const (
	TMGIIEMBMSSERVICEIDChoiceAlternativeMBMSSERVICEID TMGIIEMBMSSERVICEIDChoiceAlternative = iota
	TMGIIEMBMSSERVICEIDChoiceAlternativeMCC           TMGIIEMBMSSERVICEIDChoiceAlternative = iota
)

type TMGIIEMBMSSERVICEIDChoice struct {
	Alternative   TMGIIEMBMSSERVICEIDChoiceAlternative
	MBMSSERVICEID *TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID
	MCC           *TMGIIEMBMSSERVICEIDChoiceMCC
}
type TMGIIE struct {
	MBMSSERVICEIDChoice TMGIIEMBMSSERVICEIDChoice
	Wire                runtime.WireInfo `json:"-"`
}

func decodeEGPRSWindowSizeIEEGPRSWindowSize(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("EGPRSWindowSizeIEEGPRSWindowSize"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("5")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	if v == 31 {
		return 0, r.Error(runtime.InvalidValue, "excluded value")
	}
	r.Set("EGPRS Window Size", v)
	return uint8(v), nil
}
func encodeEGPRSWindowSizeIEEGPRSWindowSize(w *runtime.Writer, v uint8) error {
	if err := w.Enter("EGPRSWindowSizeIEEGPRSWindowSize"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("5")
	if err != nil {
		return err
	}
	if uint64(v) == 31 {
		return fmt.Errorf("excluded value")
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("EGPRS Window Size", uint64(v))
	return nil
}
func decodeEGPRSWindowSizeIE(r *runtime.Reader) (EGPRSWindowSizeIE, error) {
	if err := r.Enter("EGPRSWindowSizeIE"); err != nil {
		return EGPRSWindowSizeIE{}, err
	}
	defer r.Leave()
	var v EGPRSWindowSizeIE
	x0, err := decodeEGPRSWindowSizeIEEGPRSWindowSize(r)
	if err != nil {
		return EGPRSWindowSizeIE{}, err
	}
	v.EGPRSWindowSize = x0
	return v, nil
}
func encodeEGPRSWindowSizeIE(w *runtime.Writer, v EGPRSWindowSizeIE) error {
	if err := w.Enter("EGPRSWindowSizeIE"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 1
	if n, ok := w.Truncation("EGPRSWindowSizeIE"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeEGPRSWindowSizeIEEGPRSWindowSize(w, v.EGPRSWindowSize); err != nil {
			return err
		}
	}
	return nil
}
func decodeEGPRSModulationAndCodingIEEGPRSModulationAndCodingScheme(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("EGPRSModulationAndCodingIEEGPRSModulationAndCodingScheme"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("4")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	if uint64(v) > 11 {
		return 0, r.Error(runtime.InvalidValue, "value reserved by source table")
	}
	r.Set("EGPRS Modulation and Coding Scheme", v)
	return uint8(v), nil
}
func encodeEGPRSModulationAndCodingIEEGPRSModulationAndCodingScheme(w *runtime.Writer, v uint8) error {
	if err := w.Enter("EGPRSModulationAndCodingIEEGPRSModulationAndCodingScheme"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("4")
	if err != nil {
		return err
	}
	if uint64(v) > 11 {
		return fmt.Errorf("value reserved by source table")
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("EGPRS Modulation and Coding Scheme", uint64(v))
	return nil
}
func decodeEGPRSModulationAndCodingIE(r *runtime.Reader) (EGPRSModulationAndCodingIE, error) {
	if err := r.Enter("EGPRSModulationAndCodingIE"); err != nil {
		return EGPRSModulationAndCodingIE{}, err
	}
	defer r.Leave()
	var v EGPRSModulationAndCodingIE
	x0, err := decodeEGPRSModulationAndCodingIEEGPRSModulationAndCodingScheme(r)
	if err != nil {
		return EGPRSModulationAndCodingIE{}, err
	}
	v.EGPRSModulationAndCodingScheme = x0
	return v, nil
}
func encodeEGPRSModulationAndCodingIE(w *runtime.Writer, v EGPRSModulationAndCodingIE) error {
	if err := w.Enter("EGPRSModulationAndCodingIE"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 1
	if n, ok := w.Truncation("EGPRSModulationAndCodingIE"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeEGPRSModulationAndCodingIEEGPRSModulationAndCodingScheme(w, v.EGPRSModulationAndCodingScheme); err != nil {
			return err
		}
	}
	return nil
}
func decodeEGPRSLevelIEEGPRSLevel(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("EGPRSLevelIEEGPRSLevel"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("2")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	if v == 3 {
		return 0, r.Error(runtime.InvalidValue, "excluded value")
	}
	r.Set("EGPRS Level", v)
	return uint8(v), nil
}
func encodeEGPRSLevelIEEGPRSLevel(w *runtime.Writer, v uint8) error {
	if err := w.Enter("EGPRSLevelIEEGPRSLevel"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("2")
	if err != nil {
		return err
	}
	if uint64(v) == 3 {
		return fmt.Errorf("excluded value")
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("EGPRS Level", uint64(v))
	return nil
}
func decodeEGPRSLevelIE(r *runtime.Reader) (EGPRSLevelIE, error) {
	if err := r.Enter("EGPRSLevelIE"); err != nil {
		return EGPRSLevelIE{}, err
	}
	defer r.Leave()
	var v EGPRSLevelIE
	x0, err := decodeEGPRSLevelIEEGPRSLevel(r)
	if err != nil {
		return EGPRSLevelIE{}, err
	}
	v.EGPRSLevel = x0
	return v, nil
}
func encodeEGPRSLevelIE(w *runtime.Writer, v EGPRSLevelIE) error {
	if err := w.Enter("EGPRSLevelIE"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 1
	if n, ok := w.Truncation("EGPRSLevelIE"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeEGPRSLevelIEEGPRSLevel(w, v.EGPRSLevel); err != nil {
			return err
		}
	}
	return nil
}
func decodePacketTimingAdvanceIETIMINGADVANCEVALUEValue(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("PacketTimingAdvanceIETIMINGADVANCEVALUEValue"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("6")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("TIMING_ADVANCE_VALUE", v)
	return uint8(v), nil
}
func encodePacketTimingAdvanceIETIMINGADVANCEVALUEValue(w *runtime.Writer, v uint8) error {
	if err := w.Enter("PacketTimingAdvanceIETIMINGADVANCEVALUEValue"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("6")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("TIMING_ADVANCE_VALUE", uint64(v))
	return nil
}
func decodePacketTimingAdvanceIETIMINGADVANCEVALUESelector(r *runtime.Reader) (*uint8, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodePacketTimingAdvanceIETIMINGADVANCEVALUEValue(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodePacketTimingAdvanceIETIMINGADVANCEVALUESelector(w *runtime.Writer, v *uint8) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodePacketTimingAdvanceIETIMINGADVANCEVALUEValue(w, *v)
}
func decodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCEINDEX(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("PacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCEINDEX"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("4")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("TIMING_ADVANCE_INDEX", v)
	return uint8(v), nil
}
func encodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCEINDEX(w *runtime.Writer, v uint8) error {
	if err := w.Enter("PacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCEINDEX"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("4")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("TIMING_ADVANCE_INDEX", uint64(v))
	return nil
}
func decodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCETIMESLOTNUMBER(r *runtime.Reader) (uint8, error) {
	if err := r.Enter("PacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCETIMESLOTNUMBER"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("3")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("TIMING_ADVANCE_TIMESLOT_NUMBER", v)
	return uint8(v), nil
}
func encodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCETIMESLOTNUMBER(w *runtime.Writer, v uint8) error {
	if err := w.Enter("PacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCETIMESLOTNUMBER"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("3")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("TIMING_ADVANCE_TIMESLOT_NUMBER", uint64(v))
	return nil
}
func decodePacketTimingAdvanceIETIMINGADVANCEINDEXGroup(r *runtime.Reader) (PacketTimingAdvanceIETIMINGADVANCEINDEXGroup, error) {
	if err := r.Enter("PacketTimingAdvanceIETIMINGADVANCEINDEXGroup"); err != nil {
		return PacketTimingAdvanceIETIMINGADVANCEINDEXGroup{}, err
	}
	defer r.Leave()
	var v PacketTimingAdvanceIETIMINGADVANCEINDEXGroup
	x0, err := decodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCEINDEX(r)
	if err != nil {
		return PacketTimingAdvanceIETIMINGADVANCEINDEXGroup{}, err
	}
	v.TIMINGADVANCEINDEX = x0
	x1, err := decodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCETIMESLOTNUMBER(r)
	if err != nil {
		return PacketTimingAdvanceIETIMINGADVANCEINDEXGroup{}, err
	}
	v.TIMINGADVANCETIMESLOTNUMBER = x1
	return v, nil
}
func encodePacketTimingAdvanceIETIMINGADVANCEINDEXGroup(w *runtime.Writer, v PacketTimingAdvanceIETIMINGADVANCEINDEXGroup) error {
	if err := w.Enter("PacketTimingAdvanceIETIMINGADVANCEINDEXGroup"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("PacketTimingAdvanceIETIMINGADVANCEINDEXGroup"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCEINDEX(w, v.TIMINGADVANCEINDEX); err != nil {
			return err
		}
	}
	if limit > 1 {
		if err := encodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupTIMINGADVANCETIMESLOTNUMBER(w, v.TIMINGADVANCETIMESLOTNUMBER); err != nil {
			return err
		}
	}
	return nil
}
func decodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupSelector(r *runtime.Reader) (*PacketTimingAdvanceIETIMINGADVANCEINDEXGroup, error) {
	candidate := r.Fork()
	if err := candidate.Expect("0"); err == nil {
		r.Commit(candidate)
		return nil, nil
	}
	candidate = r.Fork()
	if err := candidate.Expect("1"); err != nil {
		return nil, r.Error(runtime.InvalidBranch, "optional selector has no matching alternative")
	}
	v, err := decodePacketTimingAdvanceIETIMINGADVANCEINDEXGroup(candidate)
	if err != nil {
		return nil, err
	}
	r.Commit(candidate)
	return &v, nil
}
func encodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupSelector(w *runtime.Writer, v *PacketTimingAdvanceIETIMINGADVANCEINDEXGroup) error {
	if v == nil {
		return w.WriteLiteral("0")
	}
	if err := w.WriteLiteral("1"); err != nil {
		return err
	}
	return encodePacketTimingAdvanceIETIMINGADVANCEINDEXGroup(w, *v)
}
func decodePacketTimingAdvanceIE(r *runtime.Reader) (PacketTimingAdvanceIE, error) {
	if err := r.Enter("PacketTimingAdvanceIE"); err != nil {
		return PacketTimingAdvanceIE{}, err
	}
	defer r.Leave()
	var v PacketTimingAdvanceIE
	x0, err := decodePacketTimingAdvanceIETIMINGADVANCEVALUESelector(r)
	if err != nil {
		return PacketTimingAdvanceIE{}, err
	}
	v.TIMINGADVANCEVALUE = x0
	x1, err := decodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupSelector(r)
	if err != nil {
		return PacketTimingAdvanceIE{}, err
	}
	v.TIMINGADVANCEINDEXGroup = x1
	return v, nil
}
func encodePacketTimingAdvanceIE(w *runtime.Writer, v PacketTimingAdvanceIE) error {
	if err := w.Enter("PacketTimingAdvanceIE"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("PacketTimingAdvanceIE"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodePacketTimingAdvanceIETIMINGADVANCEVALUESelector(w, v.TIMINGADVANCEVALUE); err != nil {
			return err
		}
	}
	if limit > 1 {
		if err := encodePacketTimingAdvanceIETIMINGADVANCEINDEXGroupSelector(w, v.TIMINGADVANCEINDEXGroup); err != nil {
			return err
		}
	}
	return nil
}
func decodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDAlt0(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDAlt0"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("0")
}
func encodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDAlt0(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("0")
}
func decodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDMBMSSERVICEID(r *runtime.Reader) (uint32, error) {
	if err := r.Enter("TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDMBMSSERVICEID"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("24")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("MBMS SERVICE ID", v)
	return uint32(v), nil
}
func encodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDMBMSSERVICEID(w *runtime.Writer, v uint32) error {
	if err := w.Enter("TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDMBMSSERVICEID"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("24")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("MBMS SERVICE ID", uint64(v))
	return nil
}
func decodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID(r *runtime.Reader) (TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID, error) {
	if err := r.Enter("TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID"); err != nil {
		return TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID{}, err
	}
	defer r.Leave()
	var v TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID
	x0, err := decodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDAlt0(r)
	if err != nil {
		return TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID{}, err
	}
	_ = x0
	x1, err := decodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDMBMSSERVICEID(r)
	if err != nil {
		return TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID{}, err
	}
	v.MBMSSERVICEID = x1
	return v, nil
}
func encodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID(w *runtime.Writer, v TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID) error {
	if err := w.Enter("TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 2
	if n, ok := w.Truncation("TMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDAlt0(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit > 1 {
		if err := encodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEIDMBMSSERVICEID(w, v.MBMSSERVICEID); err != nil {
			return err
		}
	}
	return nil
}
func decodeTMGIIEMBMSSERVICEIDChoiceMCCAlt1(r *runtime.Reader) (struct{}, error) {
	if err := r.Enter("TMGIIEMBMSSERVICEIDChoiceMCCAlt1"); err != nil {
		return struct{}{}, err
	}
	defer r.Leave()
	return struct{}{}, r.Expect("1")
}
func encodeTMGIIEMBMSSERVICEIDChoiceMCCAlt1(w *runtime.Writer, _ struct{}) error {
	return w.WriteLiteral("1")
}
func decodeTMGIIEMBMSSERVICEIDChoiceMCCMBMSSERVICEID(r *runtime.Reader) (uint32, error) {
	if err := r.Enter("TMGIIEMBMSSERVICEIDChoiceMCCMBMSSERVICEID"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("24")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("MBMS SERVICE ID", v)
	return uint32(v), nil
}
func encodeTMGIIEMBMSSERVICEIDChoiceMCCMBMSSERVICEID(w *runtime.Writer, v uint32) error {
	if err := w.Enter("TMGIIEMBMSSERVICEIDChoiceMCCMBMSSERVICEID"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("24")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("MBMS SERVICE ID", uint64(v))
	return nil
}
func decodeTMGIIEMBMSSERVICEIDChoiceMCCMCC(r *runtime.Reader) (uint16, error) {
	if err := r.Enter("TMGIIEMBMSSERVICEIDChoiceMCCMCC"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("12")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("MCC", v)
	return uint16(v), nil
}
func encodeTMGIIEMBMSSERVICEIDChoiceMCCMCC(w *runtime.Writer, v uint16) error {
	if err := w.Enter("TMGIIEMBMSSERVICEIDChoiceMCCMCC"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("12")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("MCC", uint64(v))
	return nil
}
func decodeTMGIIEMBMSSERVICEIDChoiceMCCMNC(r *runtime.Reader) (uint16, error) {
	if err := r.Enter("TMGIIEMBMSSERVICEIDChoiceMCCMNC"); err != nil {
		return 0, err
	}
	defer r.Leave()
	width, err := r.Eval("12")
	if err != nil {
		return 0, err
	}
	v, err := r.ReadUint(width)
	if err != nil {
		return 0, err
	}
	r.Set("MNC", v)
	return uint16(v), nil
}
func encodeTMGIIEMBMSSERVICEIDChoiceMCCMNC(w *runtime.Writer, v uint16) error {
	if err := w.Enter("TMGIIEMBMSSERVICEIDChoiceMCCMNC"); err != nil {
		return err
	}
	defer w.Leave()
	width, err := w.Eval("12")
	if err != nil {
		return err
	}
	if err := w.WriteUint(uint64(v), width); err != nil {
		return err
	}
	w.Set("MNC", uint64(v))
	return nil
}
func decodeTMGIIEMBMSSERVICEIDChoiceMCC(r *runtime.Reader) (TMGIIEMBMSSERVICEIDChoiceMCC, error) {
	if err := r.Enter("TMGIIEMBMSSERVICEIDChoiceMCC"); err != nil {
		return TMGIIEMBMSSERVICEIDChoiceMCC{}, err
	}
	defer r.Leave()
	var v TMGIIEMBMSSERVICEIDChoiceMCC
	x0, err := decodeTMGIIEMBMSSERVICEIDChoiceMCCAlt1(r)
	if err != nil {
		return TMGIIEMBMSSERVICEIDChoiceMCC{}, err
	}
	_ = x0
	x1, err := decodeTMGIIEMBMSSERVICEIDChoiceMCCMBMSSERVICEID(r)
	if err != nil {
		return TMGIIEMBMSSERVICEIDChoiceMCC{}, err
	}
	v.MBMSSERVICEID = x1
	x2, err := decodeTMGIIEMBMSSERVICEIDChoiceMCCMCC(r)
	if err != nil {
		return TMGIIEMBMSSERVICEIDChoiceMCC{}, err
	}
	v.MCC = x2
	x3, err := decodeTMGIIEMBMSSERVICEIDChoiceMCCMNC(r)
	if err != nil {
		return TMGIIEMBMSSERVICEIDChoiceMCC{}, err
	}
	v.MNC = x3
	return v, nil
}
func encodeTMGIIEMBMSSERVICEIDChoiceMCC(w *runtime.Writer, v TMGIIEMBMSSERVICEIDChoiceMCC) error {
	if err := w.Enter("TMGIIEMBMSSERVICEIDChoiceMCC"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 4
	if n, ok := w.Truncation("TMGIIEMBMSSERVICEIDChoiceMCC"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeTMGIIEMBMSSERVICEIDChoiceMCCAlt1(w, struct{}{}); err != nil {
			return err
		}
	}
	if limit > 1 {
		if err := encodeTMGIIEMBMSSERVICEIDChoiceMCCMBMSSERVICEID(w, v.MBMSSERVICEID); err != nil {
			return err
		}
	}
	if limit > 2 {
		if err := encodeTMGIIEMBMSSERVICEIDChoiceMCCMCC(w, v.MCC); err != nil {
			return err
		}
	}
	if limit > 3 {
		if err := encodeTMGIIEMBMSSERVICEIDChoiceMCCMNC(w, v.MNC); err != nil {
			return err
		}
	}
	return nil
}
func decodeTMGIIEMBMSSERVICEIDChoice(r *runtime.Reader) (TMGIIEMBMSSERVICEIDChoice, error) {
	var result TMGIIEMBMSSERVICEIDChoice
	matches := 0
	var chosen *runtime.Reader
	{
		candidate := r.Fork()
		v, err := decodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID(candidate)
		if err == nil {
			matches++
			chosen = candidate
			_ = v
			result.Alternative = TMGIIEMBMSSERVICEIDChoiceAlternativeMBMSSERVICEID
			result.MBMSSERVICEID = &v
		}
	}
	{
		candidate := r.Fork()
		v, err := decodeTMGIIEMBMSSERVICEIDChoiceMCC(candidate)
		if err == nil {
			matches++
			chosen = candidate
			_ = v
			result.Alternative = TMGIIEMBMSSERVICEIDChoiceAlternativeMCC
			result.MCC = &v
		}
	}
	if matches != 1 {
		return result, r.Error(runtime.InvalidBranch, fmt.Sprintf("choice has %d matching alternatives", matches))
	}
	r.Commit(chosen)
	return result, nil
}
func encodeTMGIIEMBMSSERVICEIDChoice(w *runtime.Writer, v TMGIIEMBMSSERVICEIDChoice) error {
	count := 0
	if v.MBMSSERVICEID != nil {
		count++
	}
	if v.MCC != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("choice requires exactly one alternative")
	}
	switch v.Alternative {
	case TMGIIEMBMSSERVICEIDChoiceAlternativeMBMSSERVICEID:
		if v.MBMSSERVICEID == nil {
			return fmt.Errorf("choice alternative mismatch")
		}
		return encodeTMGIIEMBMSSERVICEIDChoiceMBMSSERVICEID(w, *v.MBMSSERVICEID)
	case TMGIIEMBMSSERVICEIDChoiceAlternativeMCC:
		if v.MCC == nil {
			return fmt.Errorf("choice alternative mismatch")
		}
		return encodeTMGIIEMBMSSERVICEIDChoiceMCC(w, *v.MCC)
	default:
		return fmt.Errorf("invalid choice alternative")
	}
}
func decodeTMGIIE(r *runtime.Reader) (TMGIIE, error) {
	if err := r.Enter("TMGIIE"); err != nil {
		return TMGIIE{}, err
	}
	defer r.Leave()
	var v TMGIIE
	x0, err := decodeTMGIIEMBMSSERVICEIDChoice(r)
	if err != nil {
		return TMGIIE{}, err
	}
	v.MBMSSERVICEIDChoice = x0
	return v, nil
}
func encodeTMGIIE(w *runtime.Writer, v TMGIIE) error {
	if err := w.Enter("TMGIIE"); err != nil {
		return err
	}
	defer w.Leave()
	limit := 1
	if n, ok := w.Truncation("TMGIIE"); ok {
		if n < 0 || n > limit {
			return fmt.Errorf("invalid truncation point")
		}
		limit = n
	}
	if limit > 0 {
		if err := encodeTMGIIEMBMSSERVICEIDChoice(w, v.MBMSSERVICEIDChoice); err != nil {
			return err
		}
	}
	return nil
}

// DecodeEGPRSWindowSizeIE decodes TS 44.060 V19.0.0 §12.5.2 <EGPRS Window Size IE>.
func DecodeEGPRSWindowSizeIEFrom(r *runtime.Reader) (EGPRSWindowSizeIE, error) {
	return decodeEGPRSWindowSizeIE(r)
}
func EncodeEGPRSWindowSizeIETo(w *runtime.Writer, v EGPRSWindowSizeIE) error {
	return encodeEGPRSWindowSizeIE(w, v)
}
func DecodeEGPRSWindowSizeIE(data []byte) (runtime.Decoded[EGPRSWindowSizeIE], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[EGPRSWindowSizeIE]{}, err
	}
	r := runtime.NewReader(data)
	r.SetZeroExtension(false)
	v, err := decodeEGPRSWindowSizeIE(r)
	if err != nil {
		return runtime.Decoded[EGPRSWindowSizeIE]{}, err
	}
	tail := r.Tail()
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[EGPRSWindowSizeIE]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeEGPRSWindowSizeIE encodes an edited or newly constructed value through direct bit operations.
func EncodeEGPRSWindowSizeIE(v EGPRSWindowSizeIE) ([]byte, error) {
	if raw, ok := runtime.OriginalIfUnchanged(v, v.Wire); ok {
		return raw, nil
	}
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	if err := encodeEGPRSWindowSizeIE(w, v); err != nil {
		return nil, err
	}
	return w.Finish(v.Wire.Tail)
}

// DecodeEGPRSModulationAndCodingIE decodes TS 44.060 V19.0.0 §12.10d <EGPRS Modulation and Coding IE>.
func DecodeEGPRSModulationAndCodingIEFrom(r *runtime.Reader) (EGPRSModulationAndCodingIE, error) {
	return decodeEGPRSModulationAndCodingIE(r)
}
func EncodeEGPRSModulationAndCodingIETo(w *runtime.Writer, v EGPRSModulationAndCodingIE) error {
	return encodeEGPRSModulationAndCodingIE(w, v)
}
func DecodeEGPRSModulationAndCodingIE(data []byte) (runtime.Decoded[EGPRSModulationAndCodingIE], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[EGPRSModulationAndCodingIE]{}, err
	}
	r := runtime.NewReader(data)
	r.SetZeroExtension(false)
	v, err := decodeEGPRSModulationAndCodingIE(r)
	if err != nil {
		return runtime.Decoded[EGPRSModulationAndCodingIE]{}, err
	}
	tail := r.Tail()
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[EGPRSModulationAndCodingIE]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeEGPRSModulationAndCodingIE encodes an edited or newly constructed value through direct bit operations.
func EncodeEGPRSModulationAndCodingIE(v EGPRSModulationAndCodingIE) ([]byte, error) {
	if raw, ok := runtime.OriginalIfUnchanged(v, v.Wire); ok {
		return raw, nil
	}
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	if err := encodeEGPRSModulationAndCodingIE(w, v); err != nil {
		return nil, err
	}
	return w.Finish(v.Wire.Tail)
}

// DecodeEGPRSLevelIE decodes TS 44.060 V19.0.0 §12.10f <EGPRS Level IE>.
func DecodeEGPRSLevelIEFrom(r *runtime.Reader) (EGPRSLevelIE, error) { return decodeEGPRSLevelIE(r) }
func EncodeEGPRSLevelIETo(w *runtime.Writer, v EGPRSLevelIE) error   { return encodeEGPRSLevelIE(w, v) }
func DecodeEGPRSLevelIE(data []byte) (runtime.Decoded[EGPRSLevelIE], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[EGPRSLevelIE]{}, err
	}
	r := runtime.NewReader(data)
	r.SetZeroExtension(false)
	v, err := decodeEGPRSLevelIE(r)
	if err != nil {
		return runtime.Decoded[EGPRSLevelIE]{}, err
	}
	tail := r.Tail()
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[EGPRSLevelIE]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeEGPRSLevelIE encodes an edited or newly constructed value through direct bit operations.
func EncodeEGPRSLevelIE(v EGPRSLevelIE) ([]byte, error) {
	if raw, ok := runtime.OriginalIfUnchanged(v, v.Wire); ok {
		return raw, nil
	}
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	if err := encodeEGPRSLevelIE(w, v); err != nil {
		return nil, err
	}
	return w.Finish(v.Wire.Tail)
}

// DecodePacketTimingAdvanceIE decodes TS 44.060 V19.0.0 §12.12 <Packet Timing Advance IE>.
func DecodePacketTimingAdvanceIEFrom(r *runtime.Reader) (PacketTimingAdvanceIE, error) {
	return decodePacketTimingAdvanceIE(r)
}
func EncodePacketTimingAdvanceIETo(w *runtime.Writer, v PacketTimingAdvanceIE) error {
	return encodePacketTimingAdvanceIE(w, v)
}
func DecodePacketTimingAdvanceIE(data []byte) (runtime.Decoded[PacketTimingAdvanceIE], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[PacketTimingAdvanceIE]{}, err
	}
	r := runtime.NewReader(data)
	r.SetZeroExtension(false)
	v, err := decodePacketTimingAdvanceIE(r)
	if err != nil {
		return runtime.Decoded[PacketTimingAdvanceIE]{}, err
	}
	tail := r.Tail()
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[PacketTimingAdvanceIE]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodePacketTimingAdvanceIE encodes an edited or newly constructed value through direct bit operations.
func EncodePacketTimingAdvanceIE(v PacketTimingAdvanceIE) ([]byte, error) {
	if raw, ok := runtime.OriginalIfUnchanged(v, v.Wire); ok {
		return raw, nil
	}
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	if err := encodePacketTimingAdvanceIE(w, v); err != nil {
		return nil, err
	}
	return w.Finish(v.Wire.Tail)
}

// DecodeTMGIIE decodes TS 44.060 V19.0.0 §12.33 <TMGI IE>.
func DecodeTMGIIEFrom(r *runtime.Reader) (TMGIIE, error) { return decodeTMGIIE(r) }
func EncodeTMGIIETo(w *runtime.Writer, v TMGIIE) error   { return encodeTMGIIE(w, v) }
func DecodeTMGIIE(data []byte) (runtime.Decoded[TMGIIE], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[TMGIIE]{}, err
	}
	r := runtime.NewReader(data)
	r.SetZeroExtension(false)
	v, err := decodeTMGIIE(r)
	if err != nil {
		return runtime.Decoded[TMGIIE]{}, err
	}
	tail := r.Tail()
	v.Wire = runtime.Seal(v, data, r.Position(), tail, r.Wire())
	return runtime.Decoded[TMGIIE]{Value: v, BitsConsumed: r.Position(), Tail: tail}, nil
}

// EncodeTMGIIE encodes an edited or newly constructed value through direct bit operations.
func EncodeTMGIIE(v TMGIIE) ([]byte, error) {
	if raw, ok := runtime.OriginalIfUnchanged(v, v.Wire); ok {
		return raw, nil
	}
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	if err := encodeTMGIIE(w, v); err != nil {
		return nil, err
	}
	return w.Finish(v.Wire.Tail)
}
func Definitions() []string {
	return []string{"EGPRS Window Size IE", "EGPRS Modulation and Coding IE", "EGPRS Level IE", "Packet Timing Advance IE", "TMGI IE"}
}
func Descriptors() []runtime.Descriptor {
	return []runtime.Descriptor{
		{Standard: "TS 44.060", Version: "19.0.0", Clause: "12.5.2", Name: "EGPRS Window Size IE", Decode: func(data []byte) (any, error) { return DecodeEGPRSWindowSizeIE(data) }, Encode: func(value any) ([]byte, error) {
			v, ok := value.(EGPRSWindowSizeIE)
			if !ok {
				return nil, fmt.Errorf("wrong value type for EGPRSWindowSizeIE")
			}
			return EncodeEGPRSWindowSizeIE(v)
		}},
		{Standard: "TS 44.060", Version: "19.0.0", Clause: "12.10d", Name: "EGPRS Modulation and Coding IE", Decode: func(data []byte) (any, error) { return DecodeEGPRSModulationAndCodingIE(data) }, Encode: func(value any) ([]byte, error) {
			v, ok := value.(EGPRSModulationAndCodingIE)
			if !ok {
				return nil, fmt.Errorf("wrong value type for EGPRSModulationAndCodingIE")
			}
			return EncodeEGPRSModulationAndCodingIE(v)
		}},
		{Standard: "TS 44.060", Version: "19.0.0", Clause: "12.10f", Name: "EGPRS Level IE", Decode: func(data []byte) (any, error) { return DecodeEGPRSLevelIE(data) }, Encode: func(value any) ([]byte, error) {
			v, ok := value.(EGPRSLevelIE)
			if !ok {
				return nil, fmt.Errorf("wrong value type for EGPRSLevelIE")
			}
			return EncodeEGPRSLevelIE(v)
		}},
		{Standard: "TS 44.060", Version: "19.0.0", Clause: "12.12", Name: "Packet Timing Advance IE", Decode: func(data []byte) (any, error) { return DecodePacketTimingAdvanceIE(data) }, Encode: func(value any) ([]byte, error) {
			v, ok := value.(PacketTimingAdvanceIE)
			if !ok {
				return nil, fmt.Errorf("wrong value type for PacketTimingAdvanceIE")
			}
			return EncodePacketTimingAdvanceIE(v)
		}},
		{Standard: "TS 44.060", Version: "19.0.0", Clause: "12.33", Name: "TMGI IE", Decode: func(data []byte) (any, error) { return DecodeTMGIIE(data) }, Encode: func(value any) ([]byte, error) {
			v, ok := value.(TMGIIE)
			if !ok {
				return nil, fmt.Errorf("wrong value type for TMGIIE")
			}
			return EncodeTMGIIE(v)
		}},
	}
}
func Lookup(name string) (runtime.Descriptor, error) {
	var matches []runtime.Descriptor
	for _, d := range Descriptors() {
		if d.Name == name {
			matches = append(matches, d)
		}
	}
	if len(matches) == 1 {
		return matches[0], nil
	}
	if len(matches) == 0 {
		return runtime.Descriptor{}, fmt.Errorf("unknown CSN.1 definition %q", name)
	}
	var clauses []string
	for _, d := range matches {
		clauses = append(clauses, d.Clause)
	}
	return runtime.Descriptor{}, fmt.Errorf("ambiguous CSN.1 definition %q in clauses %v", name, clauses)
}
func LookupClause(clause, name string) (runtime.Descriptor, error) {
	for _, d := range Descriptors() {
		if d.Clause == clause && d.Name == name {
			return d, nil
		}
	}
	return runtime.Descriptor{}, fmt.Errorf("unknown CSN.1 definition %q in clause %s", name, clause)
}
