// Code generated by csn1c from TS 24.008 V20.1.0 §10.5.1.6 and TS 36.331 V19.4.0 UE-CapabilityRAT-ContainerList; DO NOT EDIT.
// Extracted source SHA-256: fe9b53189829aa5e9b350f345f68197cb9ca1851945cbb82b5f74158a39ee3f3 (Classmark 2), 25aea756f06882c43c5483796ddd170c7ba87e187aba91108ed4c4eeff8ea825 (GERAN container).
// Package uecapability contains typed GERAN capability codecs. Plain Encode calls preserve received layout and fail if an edit changes its semantic boundary. Encode<Type>Canonical copies the value and encodes its typed fields without received layout; nested TS 24.008 capabilities apply receiver-inferred zero extension.
package uecapability

import (
	"fmt"
	"github.com/gomaja/go-csn1/runtime"
	"github.com/gomaja/go-csn1/ts24008/classmark"
	"github.com/gomaja/go-csn1/ts24008/msrac"
)

// Classmark2ValuePart contains the capabilities of TS 24.008
// V20.1.0 §10.5.1.6, figure 10.5.6 and tables 10.5.6a-b.
type Classmark2ValuePart struct {
	RevisionLevel uint8
	ESIND         bool
	// A51Unavailable is the transmitted bit: 0 means A5/1 available, 1 means unavailable (TS 24.008 §10.5.1.6, table 10.5.6a).
	A51Unavailable       bool
	RFPowerCapability    uint8
	PSCapability         bool
	SSScreeningIndicator uint8
	SMCapability         bool
	VBS                  bool
	VGCS                 bool
	FC                   bool
	CM3                  bool
	LCSVA                bool
	UCS2                 bool
	SoLSA                bool
	CMSP                 bool
	// A53Available is the transmitted bit: 1 means A5/3 available (TS 24.008 §10.5.1.6, table 10.5.6b).
	A53Available bool
	// Wire.Spare records octet 3 bit 8, octet 4 bit 8, octet 5 bit 7,
	// then A5/2 (octet 5 bit 1). Send zero; accept either received value
	// (TS 24.008 V20.1.0 figure 10.5.6 and table 10.5.6b).
	Wire runtime.WireInfo `json:"-"`
}

// ReceivedA52 reports the received A5/2 bit (TS 24.008 V20.1.0
// §10.5.1.6 table 10.5.6b). It is false for a fresh value; Wire is omitted
// from JSON. Plain encoding replays it, and canonical encoding writes zero.
func (v Classmark2ValuePart) ReceivedA52() bool {
	return len(v.Wire.Spare) > 3 && v.Wire.Spare[3].BitLength == 1 && len(v.Wire.Spare[3].Bytes) > 0 && v.Wire.Spare[3].Bytes[0]&0x80 != 0
}

func DecodeClassmark2ValuePart(data []byte) (runtime.Decoded[Classmark2ValuePart], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[Classmark2ValuePart]{}, err
	}
	if len(data) < 3 {
		return runtime.Decoded[Classmark2ValuePart]{}, fmt.Errorf("classmark 2 value part requires 3 octets")
	}
	r := runtime.NewReader(data[:3])
	var readErr error
	read := func(width int) uint8 {
		if width < 0 || width > 8 {
			readErr = fmt.Errorf("invalid Classmark 2 read width")
			return 0
		}
		value, err := r.ReadUint(width)
		if err != nil {
			readErr = err
		}
		return uint8(value)
	}
	spare := func() {
		_, err := r.ReadSpare()
		if err != nil {
			readErr = err
		}
	}
	var v Classmark2ValuePart
	spare()
	v.RevisionLevel = read(2)
	v.ESIND = read(1) != 0
	v.A51Unavailable = read(1) != 0
	v.RFPowerCapability = read(3)
	spare()
	v.PSCapability = read(1) != 0
	v.SSScreeningIndicator = read(2)
	v.SMCapability = read(1) != 0
	v.VBS = read(1) != 0
	v.VGCS = read(1) != 0
	v.FC = read(1) != 0
	v.CM3 = read(1) != 0
	spare()
	v.LCSVA = read(1) != 0
	v.UCS2 = read(1) != 0
	v.SoLSA = read(1) != 0
	v.CMSP = read(1) != 0
	v.A53Available = read(1) != 0
	spare()
	if readErr != nil {
		return runtime.Decoded[Classmark2ValuePart]{}, readErr
	}
	tail := runtime.BitString{Bytes: append([]byte(nil), data[3:]...), BitLength: (len(data) - 3) * 8}
	v.Wire = runtime.Seal(v, data, 24, tail, r.Wire())
	return runtime.Decoded[Classmark2ValuePart]{Value: v, BitsConsumed: 24, Tail: tail}, nil
}

func EncodeClassmark2ValuePart(v Classmark2ValuePart) ([]byte, error) {
	if v.RevisionLevel > 3 || v.RFPowerCapability > 7 || v.SSScreeningIndicator > 3 {
		return nil, fmt.Errorf("invalid Classmark 2 field")
	}
	if err := runtime.CheckInput(v.Wire.Tail.Bytes); err != nil {
		return nil, err
	}
	if v.Wire.Tail.BitLength < 0 || v.Wire.Tail.BitLength%8 != 0 || v.Wire.Tail.BitLength/8 != len(v.Wire.Tail.Bytes) {
		return nil, fmt.Errorf("classmark 2 tail must be whole octets")
	}
	w := runtime.NewWriter()
	w.WithWire(v.Wire)
	var writeErr error
	write := func(value uint8, width int) {
		if writeErr == nil {
			writeErr = w.WriteUint(uint64(value), width)
		}
	}
	flag := func(value bool) {
		var bit uint8
		if value {
			bit = 1
		}
		write(bit, 1)
	}
	spare := func() {
		if writeErr == nil {
			writeErr = w.WriteSpare()
		}
	}
	spare()
	write(v.RevisionLevel, 2)
	flag(v.ESIND)
	flag(v.A51Unavailable)
	write(v.RFPowerCapability, 3)
	spare()
	flag(v.PSCapability)
	write(v.SSScreeningIndicator, 2)
	flag(v.SMCapability)
	flag(v.VBS)
	flag(v.VGCS)
	flag(v.FC)
	flag(v.CM3)
	spare()
	flag(v.LCSVA)
	flag(v.UCS2)
	flag(v.SoLSA)
	flag(v.CMSP)
	flag(v.A53Available)
	spare()
	if writeErr != nil {
		return nil, writeErr
	}
	return w.Finish(v.Wire.Tail)
}

// EncodeClassmark2ValuePartCanonical encodes a copy without received wire layout.
// It returns an untyped value-constraint error for a reserved sender code
// (TS 24.008 V20.1.0 table 10.5.6a; TS 24.007 §11.4.2).
// RF codes 0..4 and 7 have a defined band/RAT interpretation; selecting the
// applicable band-specific row requires the containing radio context.
func EncodeClassmark2ValuePartCanonical(v Classmark2ValuePart) ([]byte, error) {
	if v.RevisionLevel != 1 && v.RevisionLevel != 2 {
		return nil, fmt.Errorf("value reserved by source table: TS 24.008 table 10.5.6a Revision level")
	}
	if v.RFPowerCapability == 5 || v.RFPowerCapability == 6 {
		return nil, fmt.Errorf("value reserved by source table: TS 24.008 table 10.5.6a RF Power Capability")
	}
	return EncodeClassmark2ValuePart(runtime.Canonical(v))
}

type GERANCS struct {
	Classmark2 Classmark2ValuePart
	Classmark3 classmark.Classmark3ValuePart
	Wire       runtime.WireInfo `json:"-"`
}

// DecodeGERANCS follows TS 36.331 V19.4.0 UE-CapabilityRAT-ContainerList:
// 0x33, length 3, the three Classmark 2 value octets, then the Classmark 3
// value part. The CSN.1 bit string is MSB first with final octet padding.
func DecodeGERANCS(data []byte) (runtime.Decoded[GERANCS], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[GERANCS]{}, err
	}
	if len(data) < 6 || data[0] != 0x33 || data[1] != 3 {
		return runtime.Decoded[GERANCS]{}, fmt.Errorf("invalid GERAN CS Classmark 2 TLV")
	}
	cm2, err := DecodeClassmark2ValuePart(data[2:5])
	if err != nil {
		return runtime.Decoded[GERANCS]{}, err
	}
	cm3, err := classmark.DecodeClassmark3ValuePart(data[5:])
	if err != nil {
		return runtime.Decoded[GERANCS]{}, err
	}
	v := GERANCS{Classmark2: cm2.Value, Classmark3: cm3.Value}
	v.Wire = runtime.Seal(v, data, 40+cm3.BitsConsumed, cm3.Tail, runtime.WireInfo{})
	return runtime.Decoded[GERANCS]{Value: v, BitsConsumed: 40 + cm3.BitsConsumed, Tail: cm3.Tail}, nil
}

func EncodeGERANCS(v GERANCS) ([]byte, error) {
	cm2, err := EncodeClassmark2ValuePart(v.Classmark2)
	if err != nil {
		return nil, err
	}
	if len(cm2) != 3 {
		return nil, fmt.Errorf("classmark 2 must encode to 3 octets")
	}
	cm3, err := classmark.EncodeClassmark3ValuePart(v.Classmark3)
	if err != nil {
		return nil, err
	}
	if err := runtime.CheckInput(cm3); err != nil {
		return nil, err
	}
	// TS 36.331 V19.4.0 UE-CapabilityRAT-ContainerList places five framing
	// octets before TS 24.008 V20.1.0 §10.5.1.7 Classmark 3 bits.
	// Bound the nested count before adding that framing offset on 32-bit hosts.
	if v.Classmark3.Wire.BitsConsumed < 0 || v.Classmark3.Wire.BitsConsumed > len(cm3)*8 {
		return nil, fmt.Errorf("classmark 3 consumed bit count exceeds encoded length")
	}
	out := []byte{0x33, 3}
	out = append(out, cm2...)
	out = append(out, cm3...)
	if err := runtime.CheckInput(out); err != nil {
		return nil, err
	}
	if err := v.Wire.ValidateOutput(out, 40+v.Classmark3.Wire.BitsConsumed); err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeGERANCSCanonical uses the shortest equivalent TS 24.008 V20.1.0
// §10.5.1.7 Classmark 3 value in the TS 36.331 V19.4.0 container.
// It returns the errors of EncodeClassmark2ValuePartCanonical and
// classmark.EncodeClassmark3ValuePartCanonical; its own container checks are
// untyped.
func EncodeGERANCSCanonical(v GERANCS) ([]byte, error) {
	fresh := runtime.Canonical(v)
	cm2, err := EncodeClassmark2ValuePartCanonical(fresh.Classmark2)
	if err != nil {
		return nil, err
	}
	cm3, err := classmark.EncodeClassmark3ValuePartCanonical(fresh.Classmark3)
	if err != nil {
		return nil, err
	}
	out := append([]byte{0x33, 3}, cm2...)
	out = append(out, cm3...)
	if err := runtime.CheckInput(out); err != nil {
		return nil, err
	}
	again, err := DecodeGERANCS(out)
	if err != nil {
		return nil, fmt.Errorf("canonical GERAN CS does not decode: %w", err)
	}
	if !runtime.SemanticallyEqual(v, again.Value) {
		return nil, fmt.Errorf("canonical GERAN CS changes typed semantics")
	}
	return out, nil
}

type GERANPS struct {
	Capability msrac.MSRACapabilityValuePart
	Wire       runtime.WireInfo `json:"-"`
}

// DecodeGERANPS follows TS 36.331 V19.4.0 UE-CapabilityRAT-ContainerList:
// the octet string is the TS 24.008 §10.5.5.12a value part alone.
func DecodeGERANPS(data []byte) (runtime.Decoded[GERANPS], error) {
	v, err := msrac.DecodeMSRACapabilityValuePart(data)
	if err != nil {
		return runtime.Decoded[GERANPS]{}, err
	}
	out := GERANPS{Capability: v.Value}
	out.Wire = runtime.Seal(out, data, v.BitsConsumed, v.Tail, runtime.WireInfo{})
	return runtime.Decoded[GERANPS]{Value: out, BitsConsumed: v.BitsConsumed, Tail: v.Tail}, nil
}

func EncodeGERANPS(v GERANPS) ([]byte, error) {
	out, err := msrac.EncodeMSRACapabilityValuePart(v.Capability)
	if err != nil {
		return nil, err
	}
	if err := v.Wire.ValidateOutput(out, v.Capability.Wire.BitsConsumed); err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeGERANPSCanonical uses TS 24.008 V20.1.0 §10.5.5.12a
// receiver-inferred zeros within the TS 36.331 V19.4.0 container.
// It returns the errors of msrac.EncodeMSRACapabilityValuePartCanonical; its
// own container checks are untyped.
func EncodeGERANPSCanonical(v GERANPS) ([]byte, error) {
	out, err := msrac.EncodeMSRACapabilityValuePartCanonical(v.Capability)
	if err != nil {
		return nil, err
	}
	again, err := DecodeGERANPS(out)
	if err != nil {
		return nil, fmt.Errorf("canonical GERAN PS does not decode: %w", err)
	}
	if !runtime.SemanticallyEqual(v, again.Value) {
		return nil, fmt.Errorf("canonical GERAN PS changes typed semantics")
	}
	return out, nil
}
