// Code generated by csn1c from TS 24.008 V20.1.0 §10.5.1.6 and TS 36.331 V19.4.0 UE-CapabilityRAT-ContainerList; DO NOT EDIT.
// Extracted source SHA-256: fe9b53189829aa5e9b350f345f68197cb9ca1851945cbb82b5f74158a39ee3f3 (Classmark 2), 25aea756f06882c43c5483796ddd170c7ba87e187aba91108ed4c4eeff8ea825 (GERAN container).
// Package uecapability contains typed GERAN capability codecs. Plain Encode calls preserve received layout and fail if an edit changes its semantic boundary. Encode<Type>Canonical copies the value and encodes its typed fields without received layout; nested TS 24.008 capabilities apply receiver-inferred zero extension.
package uecapability

import (
	"fmt"
	"github.com/gomaja/go-csn1/runtime"
	"github.com/gomaja/go-csn1/ts24008/classmark"
	"github.com/gomaja/go-csn1/ts24008/msrac"
)

// Classmark2ValuePart contains all 24 transmitted bits of TS 24.008
// V20.1.0 §10.5.1.6, figure 10.5.6 and tables 10.5.6a-b.
type Classmark2ValuePart struct {
	Spare3        bool
	RevisionLevel uint8
	ESIND         bool
	// A51Unavailable is the transmitted bit: 0 means A5/1 available, 1 means unavailable (TS 24.008 §10.5.1.6, table 10.5.6a).
	A51Unavailable       bool
	RFPowerCapability    uint8
	Spare4               bool
	PSCapability         bool
	SSScreeningIndicator uint8
	SMCapability         bool
	VBS                  bool
	VGCS                 bool
	FC                   bool
	CM3                  bool
	Spare5               bool
	LCSVA                bool
	UCS2                 bool
	SoLSA                bool
	CMSP                 bool
	// A53Available is the transmitted bit: 1 means A5/3 available (TS 24.008 §10.5.1.6, table 10.5.6b).
	A53Available bool
	// A52ReservedBit preserves the received bit. The MS sends 0; the network accepts either value (TS 24.008 §10.5.1.6, table 10.5.6b).
	A52ReservedBit bool
	Wire           runtime.WireInfo `json:"-"`
}

func DecodeClassmark2ValuePart(data []byte) (runtime.Decoded[Classmark2ValuePart], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[Classmark2ValuePart]{}, err
	}
	if len(data) < 3 {
		return runtime.Decoded[Classmark2ValuePart]{}, fmt.Errorf("classmark 2 value part requires 3 octets")
	}
	a, b, c := data[0], data[1], data[2]
	v := Classmark2ValuePart{
		Spare3: a&0x80 != 0, RevisionLevel: (a >> 5) & 3, ESIND: a&0x10 != 0, A51Unavailable: a&0x08 != 0, RFPowerCapability: a & 7,
		Spare4: b&0x80 != 0, PSCapability: b&0x40 != 0, SSScreeningIndicator: (b >> 4) & 3, SMCapability: b&0x08 != 0, VBS: b&0x04 != 0, VGCS: b&0x02 != 0, FC: b&1 != 0,
		CM3: c&0x80 != 0, Spare5: c&0x40 != 0, LCSVA: c&0x20 != 0, UCS2: c&0x10 != 0, SoLSA: c&0x08 != 0, CMSP: c&0x04 != 0, A53Available: c&0x02 != 0, A52ReservedBit: c&1 != 0,
	}
	tail := runtime.BitString{Bytes: append([]byte(nil), data[3:]...), BitLength: (len(data) - 3) * 8}
	v.Wire = runtime.Seal(v, data, 24, tail, runtime.WireInfo{})
	return runtime.Decoded[Classmark2ValuePart]{Value: v, BitsConsumed: 24, Tail: tail}, nil
}

func EncodeClassmark2ValuePart(v Classmark2ValuePart) ([]byte, error) {
	if v.RevisionLevel > 3 || v.RFPowerCapability > 7 || v.SSScreeningIndicator > 3 {
		return nil, fmt.Errorf("invalid Classmark 2 field")
	}
	if err := runtime.CheckInput(v.Wire.Tail.Bytes); err != nil {
		return nil, err
	}
	if v.Wire.Tail.BitLength < 0 || v.Wire.Tail.BitLength%8 != 0 || v.Wire.Tail.BitLength/8 != len(v.Wire.Tail.Bytes) {
		return nil, fmt.Errorf("classmark 2 tail must be whole octets")
	}
	var a, b, c byte
	if v.Spare3 {
		a |= 0x80
	}
	a |= v.RevisionLevel << 5
	if v.ESIND {
		a |= 0x10
	}
	if v.A51Unavailable {
		a |= 0x08
	}
	a |= v.RFPowerCapability
	if v.Spare4 {
		b |= 0x80
	}
	if v.PSCapability {
		b |= 0x40
	}
	b |= v.SSScreeningIndicator << 4
	if v.SMCapability {
		b |= 0x08
	}
	if v.VBS {
		b |= 0x04
	}
	if v.VGCS {
		b |= 0x02
	}
	if v.FC {
		b |= 1
	}
	if v.CM3 {
		c |= 0x80
	}
	if v.Spare5 {
		c |= 0x40
	}
	if v.LCSVA {
		c |= 0x20
	}
	if v.UCS2 {
		c |= 0x10
	}
	if v.SoLSA {
		c |= 0x08
	}
	if v.CMSP {
		c |= 0x04
	}
	if v.A53Available {
		c |= 0x02
	}
	if v.A52ReservedBit {
		c |= 1
	}
	out := []byte{a, b, c}
	out = append(out, v.Wire.Tail.Bytes...)
	if err := v.Wire.ValidateOutput(out, 24); err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeClassmark2ValuePartCanonical encodes a copy without received wire layout.
func EncodeClassmark2ValuePartCanonical(v Classmark2ValuePart) ([]byte, error) {
	return EncodeClassmark2ValuePart(runtime.Canonical(v))
}

type GERANCS struct {
	Classmark2 Classmark2ValuePart
	Classmark3 classmark.Classmark3ValuePart
	Wire       runtime.WireInfo `json:"-"`
}

// DecodeGERANCS follows TS 36.331 V19.4.0 UE-CapabilityRAT-ContainerList:
// 0x33, length 3, the three Classmark 2 value octets, then the Classmark 3
// value part. The CSN.1 bit string is MSB first with final octet padding.
func DecodeGERANCS(data []byte) (runtime.Decoded[GERANCS], error) {
	if err := runtime.CheckInput(data); err != nil {
		return runtime.Decoded[GERANCS]{}, err
	}
	if len(data) < 6 || data[0] != 0x33 || data[1] != 3 {
		return runtime.Decoded[GERANCS]{}, fmt.Errorf("invalid GERAN CS Classmark 2 TLV")
	}
	cm2, err := DecodeClassmark2ValuePart(data[2:5])
	if err != nil {
		return runtime.Decoded[GERANCS]{}, err
	}
	cm3, err := classmark.DecodeClassmark3ValuePart(data[5:])
	if err != nil {
		return runtime.Decoded[GERANCS]{}, err
	}
	v := GERANCS{Classmark2: cm2.Value, Classmark3: cm3.Value}
	v.Wire = runtime.Seal(v, data, 40+cm3.BitsConsumed, cm3.Tail, runtime.WireInfo{})
	return runtime.Decoded[GERANCS]{Value: v, BitsConsumed: 40 + cm3.BitsConsumed, Tail: cm3.Tail}, nil
}

func EncodeGERANCS(v GERANCS) ([]byte, error) {
	cm2, err := EncodeClassmark2ValuePart(v.Classmark2)
	if err != nil {
		return nil, err
	}
	if len(cm2) != 3 {
		return nil, fmt.Errorf("classmark 2 must encode to 3 octets")
	}
	cm3, err := classmark.EncodeClassmark3ValuePart(v.Classmark3)
	if err != nil {
		return nil, err
	}
	if err := runtime.CheckInput(cm3); err != nil {
		return nil, err
	}
	// TS 36.331 V19.4.0 UE-CapabilityRAT-ContainerList places five framing
	// octets before TS 24.008 V20.1.0 §10.5.1.7 Classmark 3 bits.
	// Bound the nested count before adding that framing offset on 32-bit hosts.
	if v.Classmark3.Wire.BitsConsumed < 0 || v.Classmark3.Wire.BitsConsumed > len(cm3)*8 {
		return nil, fmt.Errorf("classmark 3 consumed bit count exceeds encoded length")
	}
	out := []byte{0x33, 3}
	out = append(out, cm2...)
	out = append(out, cm3...)
	if err := runtime.CheckInput(out); err != nil {
		return nil, err
	}
	if err := v.Wire.ValidateOutput(out, 40+v.Classmark3.Wire.BitsConsumed); err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeGERANCSCanonical uses the shortest equivalent TS 24.008 V20.1.0
// §10.5.1.7 Classmark 3 value in the TS 36.331 V19.4.0 container.
func EncodeGERANCSCanonical(v GERANCS) ([]byte, error) {
	fresh := runtime.Canonical(v)
	cm2, err := EncodeClassmark2ValuePartCanonical(fresh.Classmark2)
	if err != nil {
		return nil, err
	}
	cm3, err := classmark.EncodeClassmark3ValuePartCanonical(fresh.Classmark3)
	if err != nil {
		return nil, err
	}
	out := append([]byte{0x33, 3}, cm2...)
	out = append(out, cm3...)
	if err := runtime.CheckInput(out); err != nil {
		return nil, err
	}
	again, err := DecodeGERANCS(out)
	if err != nil {
		return nil, fmt.Errorf("canonical GERAN CS does not decode: %w", err)
	}
	if !runtime.SemanticallyEqual(v, again.Value) {
		return nil, fmt.Errorf("canonical GERAN CS changes typed semantics")
	}
	return out, nil
}

type GERANPS struct {
	Capability msrac.MSRACapabilityValuePart
	Wire       runtime.WireInfo `json:"-"`
}

// DecodeGERANPS follows TS 36.331 V19.4.0 UE-CapabilityRAT-ContainerList:
// the octet string is the TS 24.008 §10.5.5.12a value part alone.
func DecodeGERANPS(data []byte) (runtime.Decoded[GERANPS], error) {
	v, err := msrac.DecodeMSRACapabilityValuePart(data)
	if err != nil {
		return runtime.Decoded[GERANPS]{}, err
	}
	out := GERANPS{Capability: v.Value}
	out.Wire = runtime.Seal(out, data, v.BitsConsumed, v.Tail, runtime.WireInfo{})
	return runtime.Decoded[GERANPS]{Value: out, BitsConsumed: v.BitsConsumed, Tail: v.Tail}, nil
}

func EncodeGERANPS(v GERANPS) ([]byte, error) {
	out, err := msrac.EncodeMSRACapabilityValuePart(v.Capability)
	if err != nil {
		return nil, err
	}
	if err := v.Wire.ValidateOutput(out, v.Capability.Wire.BitsConsumed); err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeGERANPSCanonical uses TS 24.008 V20.1.0 §10.5.5.12a
// receiver-inferred zeros within the TS 36.331 V19.4.0 container.
func EncodeGERANPSCanonical(v GERANPS) ([]byte, error) {
	out, err := msrac.EncodeMSRACapabilityValuePartCanonical(v.Capability)
	if err != nil {
		return nil, err
	}
	again, err := DecodeGERANPS(out)
	if err != nil {
		return nil, fmt.Errorf("canonical GERAN PS does not decode: %w", err)
	}
	if !runtime.SemanticallyEqual(v, again.Value) {
		return nil, fmt.Errorf("canonical GERAN PS changes typed semantics")
	}
	return out, nil
}
