package arithaudit

import (
	"fmt"
	"go/ast"
	"regexp"
	"strings"
)

var generatedWhitespace = regexp.MustCompile(`\s+`)

// checkGeneratedResidual verifies the remaining generator patterns against the
// guard and operation in each emitted function. This is a local pattern check,
// not a full control-flow proof. The allow-list cites the generating statements.
func (c *citationChecker) checkGeneratedResidual(f Finding) error {
	file, err := c.source(f.File)
	if err != nil {
		return err
	}
	fn := functionAt(file, f.Line)
	if fn == nil {
		return fmt.Errorf("generated finding outside function: %s", f.Key())
	}
	start, end := file.set.Position(fn.Pos()).Offset, file.set.Position(fn.End()).Offset
	body := generatedWhitespace.ReplaceAllString(string(file.source[start:end]), "")
	var ordered []string
	switch f.Expression {
	case "uint64(value)", "uint8(value)":
		// The Classmark 2 helpers pin an unsigned byte writer parameter
		// and a reader width of at most eight bits on every target.
		want := "func(valueuint8,widthint){ifwriteErr==nil{writeErr=w.WriteUint(uint64(value),width)}}"
		if f.Expression == "uint8(value)" {
			want = "func(widthint)uint8{ifwidth<0||width>8{readErr=fmt.Errorf(\"invalidClassmark2readwidth\");return0};value,err:=r.ReadUint(width);iferr!=nil{readErr=err};returnuint8(value)}"
		}
		proven := false
		ast.Inspect(fn.Body, func(node ast.Node) bool {
			literal, ok := node.(*ast.FuncLit)
			if !ok || file.set.Position(literal.Pos()).Line > f.Line || file.set.Position(literal.End()).Line < f.Line {
				return true
			}
			start, end := file.set.Position(literal.Pos()).Offset, file.set.Position(literal.End()).Offset
			// Pin the complete helper body so an inner shadow or changed
			// source of value cannot inherit this proof.
			proven = strings.ReplaceAll(generatedWhitespace.ReplaceAllString(string(file.source[start:end]), ""), ";", "") == strings.ReplaceAll(want, ";", "")
			return true
		})
		if !proven {
			return fmt.Errorf("generated byte conversion lacks the bounded helper: %s", f.Key())
		}
		return nil
	case "w.Position() - before":
		ordered = []string{"before:=w.Position()", "iferr:=encode", "ifw.Position()-before!=length"}
	case "r.Position() - 1", "uint64(runtime.LHBit('H', r.Position()-1))", "uint64(runtime.LHBit('L', r.Position()-1))":
		ordered = []string{"r.Eval(\"1\")", "r.ReadUint(width)", "iferr!=nil{return", "r.Position()-1"}
	case "uint64(runtime.LHBit('H', w.Position()))", "uint64(runtime.LHBit('L', w.Position()))":
		ordered = []string{"w.Eval(\"1\")", "runtime.LHBit(", "w.Position()"}
	case "(len(data) - 3) * 8", "len(data) - 3":
		ordered = []string{"runtime.CheckInput(data)", "iflen(data)<3", "len(data)-3"}
	case "40 + cm3.BitsConsumed":
		ordered = []string{"runtime.CheckInput(data)", "iflen(data)<6", "classmark.DecodeClassmark3ValuePart(data[5:])", "40+cm3.BitsConsumed"}
	case "40 + v.Classmark3.Wire.BitsConsumed":
		ordered = []string{"runtime.CheckInput(cm3)", "v.Classmark3.Wire.BitsConsumed>len(cm3)*8", "runtime.CheckInput(out)", "40+v.Classmark3.Wire.BitsConsumed"}
	case "r.Position() + r.Remaining()":
		ordered = []string{"decodeMSRACapabilityValuePartMSRACapabilityValuePartStruct(r)", "iferr!=nil{return", "knownEnd:=r.Position()+r.Remaining()"}
	case "knownEnd - valueStart":
		ordered = []string{"valueStart:=r.Position()", "decodeMSRACapabilityValuePartMSRACapabilityValuePartStruct(r)", "iferr!=nil{return", "knownEnd:=r.Position()+r.Remaining()", "ifknownEnd-valueStart>400"}
	case "valueStart + 400":
		ordered = []string{"valueStart:=r.Position()", "knownEnd:=r.Position()+r.Remaining()", "ifknownEnd-valueStart>400{knownEnd=valueStart+400}"}
	case "knownEnd - r.Position()":
		ordered = []string{"knownEnd:=r.Position()+r.Remaining()", "ifknownEnd-valueStart>400{knownEnd=valueStart+400}", "ifknownEnd<r.Position(){knownEnd=r.Position()}", "r.PushLimit(knownEnd-r.Position())"}
	case "len(cm3) * 8":
		ordered = []string{"runtime.CheckInput(cm3)", "len(cm3)*8"}
	case "v.RevisionLevel << 5", "v.SSScreeningIndicator << 4":
		ordered = []string{"v.RevisionLevel>3", "v.SSScreeningIndicator>3", generatedWhitespace.ReplaceAllString(f.Expression, "")}
	case "^uint64(0) - 1":
		ordered = []string{"^uint64(0)-1"}
	case "v += 1":
		ordered = []string{"r.Eval(\"3\")", "r.ReadUint(width)", "v+=1"}
	case "uint64(v) - 1":
		ordered = []string{"ifuint64(v)<1", "raw:=uint64(v)-1"}
	default:
		return fmt.Errorf("unverified generated expression: %s", f.Key())
	}
	for _, part := range ordered {
		at := strings.Index(body, part)
		if at < 0 {
			return fmt.Errorf("generated guard %q absent for %s", part, f.Key())
		}
		body = body[at+len(part):]
	}
	return nil
}
